// 自动生成：业务交接档案种子数据（北区代理商 + 浙江区域交接 + 上架产品台账）
// 2026-09-22 增量：来源《机构信息汇总_2026-09-20.xlsx》（机构信息 73 行→25 机构；产品清单 148 行→去重后 133 产品）
const SEED_ARCHIVES=[
 {
  "type": "代理商",
  "region": "北区",
  "name": "上海昭强科技有限公司-讯旗",
  "short": "",
  "province": "山西",
  "operator": "电信",
  "productType": "存量",
  "settle": "T+1月CPA一次性",
  "interfaceId": "1000802",
  "contract": "2026-12-31",
  "contact": "张慧",
  "todo": "",
  "daily": "",
  "groups": "",
  "notes": "",
  "settleDetail": "",
  "risk": "",
  "status": "进行中",
  "sub": []
 },
 {
  "type": "代理商",
  "region": "北区",
  "name": "深圳市予糯科技引擎有限公司",
  "short": "",
  "province": "福建",
  "operator": "移动",
  "productType": "存量",
  "settle": "T+1月CPA一次性",
  "interfaceId": "1000861",
  "contract": "2027-07-16",
  "contact": "",
  "todo": "",
  "daily": "",
  "groups": "",
  "notes": "",
  "settleDetail": "",
  "risk": "移动侧新规调整验证码，业务暂时下线中，需跟进恢复",
  "status": "进行中",
  "sub": []
 },
 {
  "type": "代理商",
  "region": "北区",
  "name": "杭州大嘴猴科技有限公司",
  "short": "读赞",
  "province": "浙江",
  "operator": "电信",
  "productType": "存量",
  "settle": "T+1:10.0000",
  "interfaceId": "1000849",
  "contract": "2027-06-25",
  "contact": "",
  "todo": "",
  "daily": "",
  "groups": "",
  "notes": "",
  "settleDetail": "",
  "risk": "上游后台易自动拉黑触点，需及时关注（快手极速版问题多，目前屏蔽中）",
  "status": "进行中",
  "sub": []
 },
 {
  "type": "代理商",
  "region": "北区",
  "name": "浙江三合通信科技有限公司",
  "short": "",
  "province": "全国",
  "operator": "移动",
  "productType": "存量",
  "settle": "按省份结算酬金80%",
  "interfaceId": "1000712",
  "contract": "到期自动顺延",
  "contact": "沈之岳",
  "todo": "",
  "daily": "",
  "groups": "",
  "notes": "前期在对分省移动产品，暂未上线",
  "settleDetail": "",
  "risk": "",
  "status": "进行中",
  "sub": []
 },
 {
  "type": "运营商",
  "region": "浙江",
  "name": "中国电信股份有限公司浙江分公司",
  "short": "浙江电信",
  "province": "浙江",
  "operator": "",
  "productType": "存量",
  "dept": "公客",
  "contact": "领导：沈源\n孙磊俊（渠道代理商管理）\n对接人-代依莹（后续会更换对接人）",
  "contract": "2025-12-31",
  "interfaceId": "聚杰接口ID：1000500",
  "todo": "沟通合同续约及对接团队",
  "daily": "1、上线邮件报备\n2、浙江电信系统后台报备",
  "groups": "浙江电信&聚杰客诉处理群\n电渠投诉单\n浙江电信&聚杰业务小分队\n浙江电信线上代理商开票沟通群\n浙江电信省级代理商沟通群\n浙江电信线上存量代理商沟通群\n浙江电信省级代理渠道能力支撑群",
  "notes": "",
  "settleDetail": "还剩余100元待结算，待合同已经到期一年后统一清算",
  "risk": "",
  "status": "进行中",
  "sub": [
   {
    "name": "浙江电信-支付宝直连",
    "productType": "",
    "contract": "2025-12-31",
    "interfaceId": "/",
    "todo": "",
    "daily": "",
    "groups": "浙江电信存量直连—聚杰支撑（钉钉）\n浙江电信✖️支付宝技术对接群（钉钉）",
    "notes": "",
    "settleDetail": ""
   }
  ]
 },
 {
  "type": "运营商",
  "region": "浙江",
  "name": "天翼视讯传媒有限公司",
  "short": "天翼视讯",
  "province": "浙江",
  "operator": "",
  "productType": "存量",
  "dept": "/",
  "contact": "对接人-蒋艳琴\n结算对接人-黄嫣绮",
  "contract": "2028-03-31",
  "interfaceId": "/",
  "todo": "/",
  "daily": "1、接收运营商结算单并编写结算报告\n2、填写对应采购台账",
  "groups": "天翼视讯结算对接群\n聚杰-天翼视讯业务对接群\n互联网推广运营群\n统一行权入口（新国脉）沟通群\n超高清信息流页面优化\n聚杰技术对接群-上海&浙江销售品（企微）",
  "notes": "留存用户结算",
  "settleDetail": "已结算至26年1-2月账期，待回款",
  "risk": "",
  "status": "进行中",
  "sub": []
 },
 {
  "type": "运营商",
  "region": "浙江",
  "name": "中国电信股份有限公司杭州分公司",
  "short": "杭州电信",
  "province": "浙江",
  "operator": "",
  "productType": "宽带",
  "dept": "/",
  "contact": "对接人-程亚兰\n合同对接：蒋海生",
  "contract": "2027-11-18",
  "interfaceId": "",
  "todo": "",
  "daily": "暂无业务",
  "groups": "",
  "notes": "",
  "settleDetail": "",
  "risk": "",
  "status": "进行中",
  "sub": [
   {
    "name": "",
    "productType": "存量-给力",
    "contract": "2026-12-31",
    "interfaceId": "1000832",
    "todo": "1、9.9元&29元橙翼包支付宝上线跟进",
    "daily": "1、关注群内和对接人消息，及时回复；\n2、关注每日订单情况，如有对比前一日订单大量异常问题，需要及时排查；\n3、日常产品配置上线；\n4、每次上线新品需要提供报备链接和页面。\n5、有交易快照",
    "groups": "杭电–聚杰存量业务对接\n杭电&聚杰结算群（宽带&存量）",
    "notes": "1、不同渠道需配置对应报备页面的交易快照\n2、结算方：浙江给力信息技术有限公司",
    "settleDetail": "已结算至26年6月账期"
   },
   {
    "name": "",
    "productType": "宽带-赋能",
    "contract": "2026-12-09",
    "interfaceId": "10001419（服务商名称：浙江赋能）",
    "todo": "/",
    "daily": "1、佣金配置\n2、产品审核\n3、跟进上线",
    "groups": "杭州-聚杰宽带技术对接群",
    "notes": "商机单：发单成功结算，40元/单\n结算方：浙江赋能电子商务有限公司",
    "settleDetail": "已结算至26年6月账期"
   }
  ]
 },
 {
  "type": "运营商",
  "region": "浙江",
  "name": "中国联合网络通信有限公司浙江省分公司",
  "short": "浙江联通",
  "province": "浙江",
  "operator": "",
  "productType": "存量",
  "dept": "公客",
  "contact": "部门副总：温文波\n三级：吴小霞\n对接人-厉炳",
  "contract": "2028-11-20",
  "interfaceId": "接口id：1000450",
  "todo": "1、4-6账期跟进聚杰对账",
  "daily": "1、关注群内和对接人消息，及时回复；\n2、关注每日订单情况，如有对比前一日订单大量异常问题，需要及时排查；\n3、日常产品配置上线；\n4、每次上线新品需要提供报备链接和页面。",
  "groups": "浙江联通&聚杰业务小分队\n浙江联通&上海聚杰结算沟通群",
  "notes": "1、支付宝渠道业务已与支付宝直连，其他渠道业务仍归聚杰直连\n2、季度结算",
  "settleDetail": "已结算至26年1-3月账期",
  "risk": "",
  "status": "进行中",
  "sub": [
   {
    "name": "浙江联通-支付宝直连",
    "productType": "",
    "contract": "/",
    "interfaceId": "/",
    "todo": "1、4-6账期跟进支付宝直连出账",
    "daily": "1、直连产品上线配合报备",
    "groups": "【CY26浙江联通】直连对接（钉钉）",
    "notes": "季度结算",
    "settleDetail": ""
   },
   {
    "name": "浙江联通",
    "productType": "宽带",
    "contract": "2026-10-20",
    "interfaceId": "",
    "todo": "",
    "daily": "暂未合作，可考虑宽带恢复",
    "groups": "",
    "notes": "",
    "settleDetail": ""
   }
  ]
 },
 {
  "type": "运营商",
  "region": "浙江",
  "name": "中国移动通信集团浙江有限公司",
  "short": "浙江移动",
  "province": "浙江",
  "operator": "",
  "productType": "存量",
  "dept": "渠道中心",
  "contact": "一把手：徐锡涛\n三级：鲍迎\n对接人：斯丹芸",
  "contract": "合同待运营商邮寄",
  "interfaceId": "",
  "todo": "1、对接接口上线，外链模式\n2、需要缴纳2万元保证金\n3、考虑支付宝直连或者突破聚杰API问题，2选1（楉涵关注）",
  "daily": "",
  "groups": "",
  "notes": "",
  "settleDetail": "",
  "risk": "",
  "status": "进行中",
  "sub": [
   {
    "name": "浙江移动-杭州",
    "productType": "宽带",
    "contract": "三方合同（27年3月14日）\n双方合同（29年4月14日）",
    "interfaceId": "10001209",
    "todo": "1、9月份联系褚立退回25年3月-26年3月合作的2万保证金\n2、26年3月开始新合作的保证金已提供，凭证也提交给材料，OA号18633，可等合同到期半年后联系退回\n3、合同是三方协议和双方协议\n4、需要研究代客下单，目前浙江移动的宽带暂未上线",
    "daily": "1、产品配置\n2、佣金配置\n3、页面浙江移动系统报备\n4、产品审核\n5、跟进上线",
    "groups": "浙江移动宽带代理商(产品支撑)\n外部分销的需求对接（宽带代理商）\n丽水结算群：分销商-聚杰-宽带\n嘉兴结算群：嘉兴移动&上海聚杰对接\n绍兴结算群：聚杰-绍兴移动结算\n台州结算群：省级渠道上海聚杰结算\n舟山结算群：舟山移动-宽带业务结算群（聚杰\n温州结算群：聚杰-温州移动\n杭州结算群：杭州移动&上海聚杰结算沟通群\n湖州结算群：聚杰-湖州移动",
    "notes": "1、6月上旬接口对接业务暂停，若需重新上线业务，则需走代客下单模式\n2、页面报备链接：https://www.zj.10086.cn/bms/###\n账户：wb_kejingxuan\n密码：D259b_wz",
    "settleDetail": "已结算至26年6月账期"
   },
   {
    "name": "浙江移动-宁波",
    "productType": "",
    "contract": "",
    "interfaceId": "",
    "todo": "",
    "daily": "",
    "groups": "",
    "notes": "",
    "settleDetail": "已结算至26年4月账期"
   },
   {
    "name": "浙江移动-湖州",
    "productType": "",
    "contract": "",
    "interfaceId": "",
    "todo": "",
    "daily": "",
    "groups": "",
    "notes": "",
    "settleDetail": "已结算至26年3-4月账期"
   },
   {
    "name": "浙江移动-金华",
    "productType": "",
    "contract": "",
    "interfaceId": "",
    "todo": "",
    "daily": "",
    "groups": "",
    "notes": "",
    "settleDetail": "已结算至26年4月账期"
   },
   {
    "name": "浙江移动-嘉兴",
    "productType": "",
    "contract": "",
    "interfaceId": "",
    "todo": "",
    "daily": "",
    "groups": "",
    "notes": "",
    "settleDetail": "已结算至26年6月账期"
   },
   {
    "name": "浙江移动-丽水",
    "productType": "",
    "contract": "",
    "interfaceId": "",
    "todo": "",
    "daily": "",
    "groups": "",
    "notes": "",
    "settleDetail": "已结算至26年5月账期"
   },
   {
    "name": "浙江移动-衢州",
    "productType": "",
    "contract": "",
    "interfaceId": "",
    "todo": "",
    "daily": "",
    "groups": "",
    "notes": "",
    "settleDetail": "已结算至26年4月账期"
   },
   {
    "name": "浙江移动-绍兴",
    "productType": "",
    "contract": "",
    "interfaceId": "",
    "todo": "",
    "daily": "",
    "groups": "",
    "notes": "",
    "settleDetail": "已结算至26年5月账期"
   },
   {
    "name": "浙江移动-台州",
    "productType": "",
    "contract": "",
    "interfaceId": "",
    "todo": "",
    "daily": "",
    "groups": "",
    "notes": "",
    "settleDetail": "已结算至26年6月账期"
   },
   {
    "name": "浙江移动-温州",
    "productType": "",
    "contract": "",
    "interfaceId": "",
    "todo": "",
    "daily": "",
    "groups": "",
    "notes": "",
    "settleDetail": "已结算至26年6月账期"
   },
   {
    "name": "浙江移动-舟山",
    "productType": "",
    "contract": "",
    "interfaceId": "",
    "todo": "",
    "daily": "",
    "groups": "",
    "notes": "",
    "settleDetail": "已结算至26年6月账期"
   }
  ]
 },
 {
  "type": "运营商",
  "region": "浙江",
  "name": "华数传媒网络有限公司",
  "short": "华数",
  "province": "浙江",
  "operator": "",
  "productType": "宽带",
  "dept": "/",
  "contact": "对接人-麻毅城",
  "contract": "2027-03-13",
  "interfaceId": "10001123",
  "todo": "1、产品涉及号卡业务，已下架，需跟进后续情况\n2、跟进结算问题",
  "daily": "1、关注群内和对接人消息，及时回复\n2、产品审核上架",
  "groups": "华数&聚杰宽带群\n华数&上海聚杰结算沟通群",
  "notes": "年度结算",
  "settleDetail": "已结算至25年1-12月账期",
  "risk": "",
  "status": "进行中",
  "sub": []
 },
 {
  "type": "运营商",
  "region": "浙江",
  "name": "中国联合网络通信有限公司杭州市分公司",
  "short": "杭州联通",
  "province": "浙江",
  "operator": "",
  "productType": "宽带",
  "dept": "/",
  "contact": "对接人-刘德雨",
  "contract": "2027-03-31",
  "interfaceId": "10001217",
  "todo": "存在结算问题，需跟进，目前无宽带在线，后期跟进情况拓展",
  "daily": "/",
  "groups": "杭州联通&上海聚杰对账沟通",
  "notes": "业务暂停",
  "settleDetail": "已结算至26年3月账期，待回款",
  "risk": "",
  "status": "进行中",
  "sub": []
 },
 {
  "type": "运营商",
  "region": "浙江",
  "name": "中国联合网络通信有限公司宁波市分公司",
  "short": "宁波联通",
  "province": "浙江",
  "operator": "",
  "productType": "宽带",
  "dept": "/",
  "contact": "对接人-柯秋波",
  "contract": "2026-06-30",
  "interfaceId": "10001289",
  "todo": "/",
  "daily": "/",
  "groups": "宁波&聚杰宽带业务合作",
  "notes": "业务暂停",
  "settleDetail": "已结算至26年3月账期",
  "risk": "",
  "status": "进行中",
  "sub": []
 },
 {
  "type": "专业公司",
  "region": "浙江",
  "name": "杭州澜派科技有限公司",
  "short": "澜派",
  "province": "浙江",
  "operator": "",
  "productType": "存量",
  "dept": "/",
  "contact": "对接人-suvie",
  "contract": "2026-04-15",
  "interfaceId": "/",
  "todo": "关注结算",
  "daily": "/",
  "groups": "澜派&聚杰结算对接群",
  "notes": "安徽电信3.17-4.1合同重签期间代理商，需跟进该期间结算",
  "settleDetail": "已结算至26年3月账期",
  "risk": "",
  "status": "进行中",
  "sub": []
 },
 {
  "type": "专业公司",
  "region": "浙江",
  "name": "安徽天枢通讯科技有限公司",
  "short": "安徽单点",
  "province": "浙江",
  "operator": "",
  "productType": "存量",
  "dept": "/",
  "contact": "对接人-虞慧军",
  "contract": "2027-01-15",
  "interfaceId": "1000810、1000813",
  "todo": "/",
  "daily": "1、关注群内和对接人消息，及时回复\n2、日常产品配置上线",
  "groups": "安徽天枢（单点）丨上海聚杰合作群",
  "notes": "业务3月底暂停",
  "settleDetail": "已结算至26年3月账期",
  "risk": "",
  "status": "进行中",
  "sub": [],
  "settle": "T+1:37.0000"
 },
 {
  "type": "运营商",
  "region": "南区",
  "name": "中国电信股份有限公司广州分公司",
  "short": "广州电信",
  "province": "广东",
  "operator": "电信",
  "productType": "存量",
  "settle": "",
  "interfaceId": "信息流鉴权接口id：1000737\n信息流不鉴权接口id：1000778",
  "contract": "",
  "contact": "陈冠南：微信名：瓦屋陈三",
  "dept": "",
  "todo": "存送产品，运营商25年说要改取消实体认证，但是到现在还没改好",
  "daily": "验证码8选6，需要插码\n有退订接口，不知道好不好使",
  "groups": "微信群",
  "notes": "【负责人】柯莹莹",
  "settleDetail": "",
  "risk": "1、电信-广州30元云电脑黄金云盘10GB流量包-T8\n已报备，不用插码，正在跟运营商确认是否可以上线推广；\n2、6月巡检，信息流已经暂停，需要核实什么时候恢复；\n3、鉴权接口已更新可以屏蔽cpcp用户的接口，待测试；",
  "status": "进行中",
  "sub": []
 },
 {
  "type": "运营商",
  "region": "南区",
  "name": "中国电信股份有限公司深圳分公司",
  "short": "深圳电信",
  "province": "广东",
  "operator": "电信",
  "productType": "存量",
  "settle": "",
  "interfaceId": "接口id：1000701",
  "contract": "",
  "contact": "黄艳-微信名：阿拉蕾",
  "dept": "",
  "todo": "/",
  "daily": "验证码8选6，需要插码",
  "groups": "微信群",
  "notes": "【负责人】柯莹莹",
  "settleDetail": "",
  "risk": "新品报备已经提交，运营商提交审核被退回，因为验证码问题（本地公司不认同省公司的验证码8选6，但是省公司又给不出文件），还需要运营侧协调，需要跟进进度；",
  "status": "进行中",
  "sub": []
 },
 {
  "type": "运营商",
  "region": "南区",
  "name": "湖南联通聚杰",
  "short": "",
  "province": "湖南",
  "operator": "联通",
  "productType": "存量",
  "settle": "",
  "interfaceId": "接口id：1000300",
  "contract": "",
  "contact": "业务：王丛堇-微信名：Lulu-瑾🌞\n结算：微信名：- -",
  "dept": "",
  "todo": "",
  "daily": "跟进产品销量\n只有固定点位",
  "groups": "企微群",
  "notes": "【负责人】赵伟宇",
  "settleDetail": "",
  "risk": "1、结算对账明细有对不上了，运营商侧正在对，需要跟进对账结果；",
  "status": "进行中",
  "sub": []
 },
 {
  "type": "运营商",
  "region": "南区",
  "name": "湖南联通讯旗",
  "short": "",
  "province": "湖南",
  "operator": "联通",
  "productType": "存量",
  "settle": "",
  "interfaceId": "接口id：1000716",
  "contract": "",
  "contact": "石璇-微信名：__X.🍃",
  "dept": "",
  "todo": "/",
  "daily": "1、关注产品质态（已接退订接口）月退订不得超过40%，不然会暂停；",
  "groups": "微信群、企微群",
  "notes": "【负责人】赵伟宇",
  "settleDetail": "",
  "risk": "1、当前因5月产品质态差，暂停推广，需要等运营商对接马良链接后（预计6月10日），在恢复推广，需要跟进运营商恢复进度；\n2、当前只剩一个已报备的产品可以跑信息流，联通-湖南都市畅听流量组合包29元(xq)运营商通知暂停，需要确定后续会不会恢复推广，如果不恢复的话，需要报备一款新品链接做备份；(报备页面先给运营商审核，没问题在全流程录屏）",
  "status": "进行中",
  "sub": []
 },
 {
  "type": "运营商",
  "region": "南区",
  "name": "湖南移动",
  "short": "",
  "province": "湖南",
  "operator": "移动",
  "productType": "存量",
  "settle": "T+1:5.0000; T+2:5.0000",
  "interfaceId": "1000674、1000796",
  "contract": "",
  "contact": "李加香-微信名：加肉肉",
  "dept": "",
  "todo": "1、插码；\n2、明星闹铃经济版科大接口对接进度；",
  "daily": "1、重点关注产品质态，日退订尽量低于25%；（湖南移动后台查询退订数据）\n2、运营商大群不定期发布黑名单号码，需要手动屏蔽；（群里不能拉客服，原则上一个公司只能留一个人在群里）",
  "groups": "微信群",
  "notes": "【负责人】赵伟宇",
  "settleDetail": "",
  "risk": "1、移动-湖南30元足球通畅享包-明星闹铃经济版，运营商报备已经完成，等待聚杰与科大的接口对接完成后，可以少量上线关注质态投放；（低于100单）\n2、湖南移动上线的产品运营商通知需要对接插码，云效需求已提交，待运营商提供插码id等参数后，继续对接；\n3、运营要求月退订率不能超过40%，超过给红牌，移动全线拉黑无法合作，需要重点关注退订；（26年已经领过一次红牌了，没有红牌的机会了）\n4、每月初申请手机号，匹配上月退订数据；\n湖南移动退订回传网址：（赵伟宇手机号登录）https://wap.hn.10086.cn/h5web/static/idiops/login.html",
  "status": "进行中",
  "sub": []
 },
 {
  "type": "代理商",
  "region": "南区",
  "name": "科大",
  "short": "",
  "province": "全国",
  "operator": "",
  "productType": "存量",
  "settle": "",
  "interfaceId": "接口id：1000820",
  "contract": "",
  "contact": "产品上下线：关键句\n报文找他：chaoyang",
  "dept": "",
  "todo": "/",
  "daily": "需要插sdk",
  "groups": "微信群",
  "notes": "【负责人】赵伟宇",
  "settleDetail": "",
  "risk": "1、电信-陕西10元视频彩铃AI制作高级包（kdxf）\n已pj，可以跟进科大是否可以投放；\n2、通助产品商品id替换；",
  "status": "进行中",
  "sub": []
 },
 {
  "type": "代理商",
  "region": "南区",
  "name": "新号吧",
  "short": "",
  "province": "广东",
  "operator": "",
  "productType": "宽带",
  "settle": "",
  "interfaceId": "服务商id：10001425",
  "contract": "",
  "contact": "微信名：华生（工作号）13144434999",
  "dept": "",
  "todo": "/",
  "daily": "/",
  "groups": "微信群",
  "notes": "【负责人】柯莹莹",
  "settleDetail": "",
  "risk": "1、跟进对方上线广东移动的产品；\n2、跟进结算",
  "status": "进行中",
  "sub": []
 },
 {
  "type": "代理商",
  "region": "南区",
  "name": "蜂助手",
  "short": "",
  "province": "全国",
  "operator": "",
  "productType": "宽带",
  "settle": "",
  "interfaceId": "服务商id：10001315",
  "contract": "",
  "contact": "微信名：蟹蟹🦀",
  "dept": "",
  "todo": "/",
  "daily": "结算跟进",
  "groups": "微信群",
  "notes": "【负责人】柯莹莹",
  "settleDetail": "",
  "risk": "宽带接口对接",
  "status": "进行中",
  "sub": []
 },
 {
  "type": "运营商",
  "region": "南区",
  "name": "河南电信（支付宝丢了）",
  "short": "",
  "province": "河南",
  "operator": "电信",
  "productType": "存量",
  "settle": "",
  "interfaceId": "固定点位接口id：1000342\n信息流接口id：1000545",
  "contract": "",
  "contact": "固定点位：李帆-微信名：Never",
  "dept": "",
  "todo": "1、固定点位产品运营商正在梳理，后会有产品调整",
  "daily": "信息流有统认",
  "groups": "",
  "notes": "【负责人】柯莹莹\n电信-河南15元电力小合约-T\n目前只有1个信息流产品\n-销量0注意下线：联通-河南30元15GB国内流量月包专属减费10元/月优惠24个月合约(河南)-立即生效，联通-河南10元5GB国内5G流量月包",
  "settleDetail": "",
  "risk": "电信-河南15元电力小合约-T\n信息流产品目前看本月可以推广，月底合同到期，需要bd沟通信息流怎么继续推广",
  "status": "进行中",
  "sub": []
 },
 {
  "type": "运营商",
  "region": "南区",
  "name": "河南电信通服",
  "short": "",
  "province": "河南",
  "operator": "电信",
  "productType": "宽带",
  "settle": "",
  "interfaceId": "服务商id：10001393",
  "contract": "",
  "contact": "容婷-微信号：胖停\n企微号：容婷",
  "dept": "",
  "todo": "/",
  "daily": "跟进结算，慢\n订单量",
  "groups": "微信群",
  "notes": "【负责人】柯莹莹",
  "settleDetail": "",
  "risk": "/",
  "status": "进行中",
  "sub": []
 },
 {
  "type": "运营商",
  "region": "南区",
  "name": "河南联通（支付宝也丢了）",
  "short": "",
  "province": "河南",
  "operator": "联通",
  "productType": "存量",
  "settle": "",
  "interfaceId": "接口id：1000432",
  "contract": "",
  "contact": "冉冉-微信名：啦啦lr",
  "dept": "",
  "todo": "/",
  "daily": "1、每月初输出上月分产品销量表格同步运营商；",
  "groups": "",
  "notes": "【负责人】柯莹莹",
  "settleDetail": "",
  "risk": "联通-河南9.9元10GB国内流量三日包\n联通-河南20元20GB国内流量假日包（7天）\n\n产品已替换完成，目前后台已经有成功订单，改版前后报备页面已同步客服文档",
  "status": "进行中",
  "sub": []
 },
 {
  "type": "运营商",
  "region": "南区",
  "name": "湖南电信",
  "short": "",
  "province": "湖南",
  "operator": "电信",
  "productType": "存量",
  "settle": "T+1:6.0000; T+2:4.0000",
  "interfaceId": "1000013、1000185、1000199、1000236、1000351、1000353、1000375、1000405、1000410、1000412、1000428、1000430、1000446、1000448、1000476、1000518、1000558、1000559、1000798、1000816、1000868",
  "contract": "",
  "contact": "日常对接：费成全-微信名：费成全\n退订数据：史策-微信名：🌲",
  "dept": "大网部门",
  "todo": "/",
  "daily": "关注【电信-湖南30元20GB月包20251118-跳转接口】质态，及时优化；（无退订接口，需要找运营商要明细进行匹配）",
  "groups": "微信群",
  "notes": "【负责人】赵伟宇",
  "settleDetail": "",
  "risk": "/",
  "status": "进行中",
  "sub": [
   {
    "name": "电信-湖南30元20GB月包20251118-跳转接口",
    "productType": "存量",
    "contract": "",
    "interfaceId": "",
    "todo": "",
    "daily": "",
    "groups": "",
    "notes": "",
    "settleDetail": ""
   },
   {
    "name": "电信-湖南30元20GB月包202404",
    "productType": "存量",
    "contract": "",
    "interfaceId": "",
    "todo": "",
    "daily": "",
    "groups": "",
    "notes": "",
    "settleDetail": ""
   },
   {
    "name": "电信-湖南30元20G月包",
    "productType": "存量",
    "contract": "",
    "interfaceId": "",
    "todo": "",
    "daily": "",
    "groups": "",
    "notes": "",
    "settleDetail": ""
   },
   {
    "name": "电信-湖南20元20GB月包202404",
    "productType": "存量",
    "contract": "",
    "interfaceId": "",
    "todo": "",
    "daily": "",
    "groups": "",
    "notes": "",
    "settleDetail": ""
   },
   {
    "name": "电信-湖南20元20GB加餐包202404",
    "productType": "存量",
    "contract": "",
    "interfaceId": "",
    "todo": "",
    "daily": "",
    "groups": "",
    "notes": "",
    "settleDetail": ""
   },
   {
    "name": "电信-湖南10元5GB月包202404",
    "productType": "存量",
    "contract": "",
    "interfaceId": "",
    "todo": "",
    "daily": "",
    "groups": "",
    "notes": "",
    "settleDetail": ""
   },
   {
    "name": "电信-湖南20元10GB提速包202404",
    "productType": "存量",
    "contract": "",
    "interfaceId": "",
    "todo": "",
    "daily": "",
    "groups": "",
    "notes": "",
    "settleDetail": ""
   },
   {
    "name": "电信-湖南5元5GB月包202404",
    "productType": "存量",
    "contract": "",
    "interfaceId": "",
    "todo": "",
    "daily": "",
    "groups": "",
    "notes": "",
    "settleDetail": ""
   },
   {
    "name": "电信-湖南50元40GB月包202404",
    "productType": "存量",
    "contract": "",
    "interfaceId": "",
    "todo": "",
    "daily": "",
    "groups": "",
    "notes": "",
    "settleDetail": ""
   },
   {
    "name": "电信-湖南15元10GB月包202404",
    "productType": "存量",
    "contract": "",
    "interfaceId": "",
    "todo": "",
    "daily": "",
    "groups": "",
    "notes": "",
    "settleDetail": ""
   },
   {
    "name": "电信-湖南10元10GB月包202404",
    "productType": "存量",
    "contract": "",
    "interfaceId": "",
    "todo": "",
    "daily": "",
    "groups": "",
    "notes": "",
    "settleDetail": ""
   },
   {
    "name": "电信-湖南70元100GB月包202404",
    "productType": "存量",
    "contract": "",
    "interfaceId": "",
    "todo": "",
    "daily": "",
    "groups": "",
    "notes": "",
    "settleDetail": ""
   },
   {
    "name": "电信-湖南20元5GB提速包202404",
    "productType": "存量",
    "contract": "",
    "interfaceId": "",
    "todo": "",
    "daily": "",
    "groups": "",
    "notes": "",
    "settleDetail": ""
   },
   {
    "name": "电信-湖南60元60GB月包202404",
    "productType": "存量",
    "contract": "",
    "interfaceId": "",
    "todo": "",
    "daily": "",
    "groups": "",
    "notes": "",
    "settleDetail": ""
   }
  ]
 },
 {
  "type": "代理商",
  "region": "南区",
  "name": "南区宽带（服务商10001185）",
  "short": "",
  "province": "",
  "operator": "",
  "productType": "宽带",
  "settle": "",
  "interfaceId": "服务商id：10001185",
  "contract": "",
  "contact": "阳晶晶-微信号：阳小虾",
  "dept": "",
  "todo": "/",
  "daily": "关注销量，销量下降时需要找原因，进行优化",
  "groups": "微信群",
  "notes": "【负责人】赵伟宇",
  "settleDetail": "",
  "risk": "宽带页面优化已提交运营审核，需要跟进审核结果后，前端页面替换上去-已完成",
  "status": "进行中",
  "sub": []
 },
 {
  "type": "代理商",
  "region": "南区",
  "name": "南区存量（服务商1000405）",
  "short": "",
  "province": "",
  "operator": "",
  "productType": "存量",
  "settle": "",
  "interfaceId": "接口id：1000405",
  "contract": "",
  "contact": "苏兵-微信号：兵兵²⁰²⁶",
  "dept": "权益部门",
  "todo": "/",
  "daily": "关注退订和销量",
  "groups": "微信群：",
  "notes": "【负责人】赵伟宇",
  "settleDetail": "",
  "risk": "需要增量：\n电信-湖南哔哩哔哩会员15GB定向流量包（19.9元/月）\n电信-湖南网易云音乐会员权益流量包（19.9元5GB+网易云",
  "status": "进行中",
  "sub": [
   {
    "name": "电信-湖南互联网畅享权益包5GB15元",
    "productType": "存量",
    "contract": "",
    "interfaceId": "",
    "todo": "",
    "daily": "",
    "groups": "",
    "notes": "",
    "settleDetail": ""
   },
   {
    "name": "电信-湖南天翼云电脑基础版（30元/月）",
    "productType": "存量",
    "contract": "",
    "interfaceId": "",
    "todo": "",
    "daily": "",
    "groups": "",
    "notes": "",
    "settleDetail": ""
   },
   {
    "name": "电信-湖南卫星+流量组合包（连续包月）",
    "productType": "存量",
    "contract": "",
    "interfaceId": "",
    "todo": "",
    "daily": "",
    "groups": "",
    "notes": "",
    "settleDetail": ""
   },
   {
    "name": "电信-湖南哔哩哔哩会员15GB定向流量包（19.9元/月）",
    "productType": "存量",
    "contract": "",
    "interfaceId": "",
    "todo": "",
    "daily": "",
    "groups": "",
    "notes": "",
    "settleDetail": ""
   },
   {
    "name": "电信-湖南网易云音乐会员权益流量包（19.9元5GB+网易云",
    "productType": "存量",
    "contract": "",
    "interfaceId": "",
    "todo": "",
    "daily": "",
    "groups": "",
    "notes": "",
    "settleDetail": ""
   }
  ]
 },
 {
  "type": "代理商",
  "region": "南区",
  "name": "号百",
  "short": "",
  "province": "全国（部分省份推广）",
  "operator": "",
  "productType": "存量",
  "settle": "",
  "interfaceId": "接口id：1000724",
  "contract": "",
  "contact": "吴优-微信号：YOU",
  "dept": "",
  "todo": "/",
  "daily": "1、结算跟进；\n2、之前沟通信息流，目前确定因为客诉问题信息流都暂停了，后续可以继续沟通；",
  "groups": "微信群：",
  "notes": "【负责人】柯莹莹",
  "settleDetail": "",
  "risk": "/",
  "status": "进行中",
  "sub": []
 },
 {
  "type": "代理商",
  "region": "南区",
  "name": "咪咕数媒（走我们接口，就是森越我们拿提成）",
  "short": "",
  "province": "全国",
  "operator": "",
  "productType": "存量",
  "settle": "",
  "interfaceId": "接口id：1000696、1000705",
  "contract": "",
  "contact": "微信名：YiYizi",
  "dept": "",
  "todo": "/",
  "daily": "/",
  "groups": "企微群",
  "notes": "【负责人】赵伟宇\n森越的商品，后续sku这里，需要把这个“是否需要统一认证”打开。因为需要将咪咕返回我们的订单号同步给森越\n一定要配推广活动，不然订单全失败",
  "settleDetail": "",
  "risk": "目前处于暂停投放状态，需要配合对方提供各种材料申请恢复投放；",
  "status": "已暂停",
  "sub": []
 },
 {
  "type": "代理商",
  "region": "西区",
  "name": "杭州英宏电子科技有限公司",
  "short": "",
  "province": "陕西",
  "operator": "移动",
  "productType": "存量",
  "settle": "T+1:18.0000",
  "interfaceId": "1000567、1000749",
  "contract": "2026-06-05（已到期）",
  "contact": "山海丶（严立）",
  "dept": "",
  "todo": "",
  "daily": "",
  "groups": "",
  "notes": "省份：陕西移动 / 吉林移动 / 新疆电信 / 辽宁移动；质态要求：退订要求高",
  "settleDetail": "结算周期：次月对账结算",
  "risk": "",
  "status": "进行中",
  "sub": []
 },
 {
  "type": "代理商",
  "region": "西区",
  "name": "西安彩拓网络科技有限公司",
  "short": "",
  "province": "宁夏",
  "operator": "电信",
  "productType": "存量",
  "settle": "CPA",
  "interfaceId": "",
  "contract": "2025-12-23（已到期）",
  "contact": "王亚辉",
  "dept": "",
  "todo": "",
  "daily": "",
  "groups": "",
  "notes": "省份：宁夏电信；质态要求：退订要求高",
  "settleDetail": "结算周期：次月对账结算",
  "risk": "",
  "status": "进行中",
  "sub": []
 },
 {
  "type": "代理商",
  "region": "西区",
  "name": "合肥乐趣信息技术有限公司",
  "short": "",
  "province": "新疆",
  "operator": "电信",
  "productType": "存量",
  "settle": "T+1:14.0000",
  "interfaceId": "1000565",
  "contract": "2025-04-30（已到期）",
  "contact": "C（陈永信）",
  "dept": "",
  "todo": "",
  "daily": "",
  "groups": "",
  "notes": "省份：新疆电信；质态要求：无要求",
  "settleDetail": "结算周期：次月对账结算",
  "risk": "",
  "status": "进行中",
  "sub": []
 },
 {
  "type": "代理商",
  "region": "西区",
  "name": "河北海哲电子科技有限公司",
  "short": "",
  "province": "贵州",
  "operator": "联通",
  "productType": "存量",
  "settle": "CPA",
  "interfaceId": "",
  "contract": "2026-02-07（已到期）",
  "contact": "李宇骞",
  "dept": "",
  "todo": "",
  "daily": "",
  "groups": "",
  "notes": "省份：贵州联通；质态要求：退订要求高，阶梯结算",
  "settleDetail": "结算周期：周结，甲乙双方于每周二前核对完成上一结算周期的佣金；考核点：按退订率投诉率阶梯结算",
  "risk": "",
  "status": "进行中",
  "sub": []
 },
 {
  "type": "代理商",
  "region": "西区",
  "name": "成都麦禾文化传播有限公司",
  "short": "",
  "province": "全国",
  "operator": "移动",
  "productType": "存量",
  "settle": "CPA",
  "interfaceId": "1000787、1000860",
  "contract": "2026-10-23",
  "contact": "董松炜",
  "dept": "",
  "todo": "",
  "daily": "",
  "groups": "",
  "notes": "省份：咪咕文化全国移动的产品，仅上线小米入口",
  "settleDetail": "结算周期：次月对账结算",
  "risk": "",
  "status": "进行中",
  "sub": []
 },
 {
  "type": "代理商",
  "region": "西区",
  "name": "湖南奇点引擎科技有限公司",
  "short": "",
  "province": "重庆",
  "operator": "电信",
  "productType": "存量",
  "settle": "CPA",
  "interfaceId": "",
  "contract": "2026-11-11",
  "contact": "汤鑫鑫",
  "dept": "",
  "todo": "",
  "daily": "",
  "groups": "",
  "notes": "省份：重庆电信；质态要求：退订要求高",
  "settleDetail": "结算周期：次月对账结算",
  "risk": "",
  "status": "进行中",
  "sub": []
 },
 {
  "type": "代理商",
  "region": "西区",
  "name": "邑航科技（北京）有限公司",
  "short": "",
  "province": "新疆",
  "operator": "电信",
  "productType": "存量",
  "settle": "T+1:12.0000",
  "interfaceId": "1000608",
  "contract": "已到期",
  "contact": "youyue0537（刘体祥）",
  "dept": "",
  "todo": "",
  "daily": "",
  "groups": "",
  "notes": "省份：新疆电信；质态要求：退订要求高",
  "settleDetail": "结算周期：次月对账结算",
  "risk": "历史待回款；结算考核点：重点盯回款",
  "status": "进行中",
  "sub": []
 },
 {
  "type": "代理商",
  "region": "西区",
  "name": "河南开心连连电子商务有限公司",
  "short": "",
  "province": "陕西",
  "operator": "联通",
  "productType": "存量",
  "settle": "CPA",
  "interfaceId": "",
  "contract": "2027-12-31",
  "contact": "胡鹏博",
  "dept": "",
  "todo": "1、老产品由于客诉7月下旬下线。最新情况：陕西联通近期巡检，等新出链接，走统认模式上线产品需pj。历史日均100单；\n2、历史发展货品参考：联通-陕西20元3GB通用优享出行权益包，1006275_106298_14055；\n3、链接：https://benefit.jujienet.com/benefit/indexP/910441/1006275；\n4、结算至7月订单",
  "daily": "",
  "groups": "",
  "notes": "省份：陕西联通；质态要求：客诉、退订要求高",
  "settleDetail": "结算周期：次月对账结算",
  "risk": "",
  "status": "进行中",
  "sub": []
 },
 {
  "type": "运营商",
  "region": "南区",
  "name": "中国移动通信集团广西有限公司",
  "short": "广西移动",
  "province": "广西",
  "operator": "移动",
  "productType": "存量",
  "settle": "T+1:6.0000",
  "interfaceId": "1000100、1000167、1000174、1000807",
  "contract": "",
  "contact": "",
  "dept": "",
  "todo": "",
  "daily": "",
  "groups": "",
  "notes": "",
  "settleDetail": "",
  "risk": "",
  "status": "进行中",
  "sub": []
 },
 {
  "type": "运营商",
  "region": "北区",
  "name": "中国联合网络通信有限公司山东省分公司",
  "short": "山东联通",
  "province": "山东",
  "operator": "联通",
  "productType": "存量",
  "settle": "",
  "interfaceId": "",
  "contract": "",
  "contact": "",
  "dept": "",
  "todo": "",
  "daily": "",
  "groups": "",
  "notes": "",
  "settleDetail": "",
  "risk": "",
  "status": "进行中",
  "sub": []
 },
 {
  "type": "运营商",
  "region": "南区",
  "name": "中国联合网络通信有限公司湖南省分公司",
  "short": "湖南联通",
  "province": "湖南",
  "operator": "联通",
  "productType": "存量",
  "settle": "T+1:3.0000",
  "interfaceId": "1000300",
  "contract": "",
  "contact": "",
  "dept": "",
  "todo": "",
  "daily": "",
  "groups": "",
  "notes": "",
  "settleDetail": "",
  "risk": "",
  "status": "进行中",
  "sub": []
 },
 {
  "type": "运营商",
  "region": "北区",
  "name": "中国电信股份有限公司山东分公司",
  "short": "山东电信",
  "province": "山东",
  "operator": "电信",
  "productType": "存量",
  "settle": "",
  "interfaceId": "",
  "contract": "",
  "contact": "",
  "dept": "",
  "todo": "",
  "daily": "",
  "groups": "",
  "notes": "",
  "settleDetail": "",
  "risk": "",
  "status": "进行中",
  "sub": []
 },
 {
  "type": "运营商",
  "region": "南区",
  "name": "中国电信股份有限公司广西分公司",
  "short": "广西电信",
  "province": "广西",
  "operator": "电信",
  "productType": "存量",
  "settle": "T+1:1.4900",
  "interfaceId": "1000227、1000237、1000291、1000314、1000315、1000316、1000320、1000324、1000377、1000378、1000390、1000391、1000392、1000401、1000440、1000833、1000851",
  "contract": "",
  "contact": "",
  "dept": "",
  "todo": "",
  "daily": "",
  "groups": "",
  "notes": "",
  "settleDetail": "",
  "risk": "",
  "status": "进行中",
  "sub": []
 },
 {
  "type": "代理商",
  "region": "南区",
  "name": "中国联合网络通信有限公司湖南省分公司（讯旗）",
  "short": "湖南联通(讯旗)",
  "province": "湖南",
  "operator": "",
  "productType": "存量",
  "settle": "",
  "interfaceId": "1000716",
  "contract": "",
  "contact": "",
  "todo": "",
  "daily": "",
  "groups": "",
  "notes": "接口提供方ID 1000804；供货方ID 1000805；结算方ID -；接口数 1",
  "settleDetail": "",
  "risk": "",
  "status": "进行中",
  "sub": []
 },
 {
  "type": "运营商",
  "region": "南区",
  "name": "中国电信股份有限公司海南分公司",
  "short": "海南电信",
  "province": "海南",
  "operator": "电信",
  "productType": "存量",
  "settle": "T+1:12.8400; T+2:12.8400; T+3:12.8400; T+4:12.8400; T+5:12.8400; T+6:12.8400",
  "interfaceId": "1000733、1000831",
  "contract": "",
  "contact": "",
  "todo": "",
  "daily": "",
  "groups": "",
  "notes": "接口提供方ID 1000846；供货方ID 1000857；结算方ID 1000858；接口数 2",
  "settleDetail": "单笔佣金 77.0400",
  "risk": "",
  "status": "进行中",
  "sub": []
 },
 {
  "type": "运营商",
  "region": "南区",
  "name": "中国联合网络通信有限公司海南省分公司",
  "short": "海南联通",
  "province": "海南",
  "operator": "联通",
  "productType": "存量",
  "settle": "T+1:8.0000",
  "interfaceId": "1000290",
  "contract": "",
  "contact": "",
  "todo": "",
  "daily": "",
  "groups": "",
  "notes": "接口提供方ID 1000086；供货方ID 1000260；结算方ID 1000432；接口数 1",
  "settleDetail": "单笔佣金 8.0000",
  "risk": "",
  "status": "进行中",
  "sub": []
 },
 {
  "type": "专业公司",
  "region": "南区",
  "name": "中移互联网有限公司",
  "short": "中移互联网",
  "province": "",
  "operator": "",
  "productType": "存量",
  "settle": "T+1:14.0000; T+2:14.0000; T+3:14.0000; T+4:14.0000; T+5:14.0000; T+6:14.0000",
  "interfaceId": "1000875",
  "contract": "",
  "contact": "",
  "todo": "",
  "daily": "",
  "groups": "",
  "notes": "接口提供方ID 1001238；供货方ID 1001239；结算方ID 1001117；接口数 1",
  "settleDetail": "单笔佣金 168.0000",
  "risk": "",
  "status": "进行中",
  "sub": []
 },
 {
  "type": "代理商",
  "region": "南区",
  "name": "北京中网云合网络科技有限公司",
  "short": "北京中网云合",
  "province": "北京",
  "operator": "",
  "productType": "存量",
  "settle": "T+1:19.0000",
  "interfaceId": "1000859",
  "contract": "",
  "contact": "",
  "todo": "",
  "daily": "",
  "groups": "",
  "notes": "接口提供方ID 1001214；供货方ID 1001215；结算方ID 1001216；接口数 1",
  "settleDetail": "单笔佣金 19.0000",
  "risk": "",
  "status": "进行中",
  "sub": []
 },
 {
  "type": "代理商",
  "region": "南区",
  "name": "南京新游科技有限公司",
  "short": "南京新游",
  "province": "江苏",
  "operator": "",
  "productType": "存量",
  "settle": "",
  "interfaceId": "1000664",
  "contract": "",
  "contact": "",
  "todo": "",
  "daily": "",
  "groups": "",
  "notes": "接口提供方ID 1000657；供货方ID 1000658；结算方ID -；接口数 1",
  "settleDetail": "",
  "risk": "",
  "status": "进行中",
  "sub": []
 },
 {
  "type": "代理商",
  "region": "南区",
  "name": "广东森越互联网科技有限公司",
  "short": "广东森越",
  "province": "广东",
  "operator": "",
  "productType": "存量",
  "settle": "T+3:13.5000; T+4:13.5000; T+5:13.5000",
  "interfaceId": "1000590、1000732",
  "contract": "",
  "contact": "",
  "todo": "",
  "daily": "",
  "groups": "",
  "notes": "接口提供方ID 1000563；供货方ID 1000564；结算方ID 1000565；接口数 2",
  "settleDetail": "单笔佣金 40.5000",
  "risk": "",
  "status": "进行中",
  "sub": []
 },
 {
  "type": "代理商",
  "region": "南区",
  "name": "济南馨馨盈通网络科技有限公司",
  "short": "济南馨馨盈通",
  "province": "山东",
  "operator": "",
  "productType": "存量",
  "settle": "T+1:14.0000",
  "interfaceId": "1000639、1000662",
  "contract": "",
  "contact": "",
  "todo": "",
  "daily": "",
  "groups": "",
  "notes": "接口提供方ID 1000631；供货方ID 1000629；结算方ID 1000630；接口数 2",
  "settleDetail": "单笔佣金 14.0000",
  "risk": "",
  "status": "进行中",
  "sub": []
 },
 {
  "type": "代理商",
  "region": "南区",
  "name": "厦门众联流量果科技有限公司",
  "short": "厦门众联流量果",
  "province": "福建",
  "operator": "",
  "productType": "存量",
  "settle": "T+1:23.7400",
  "interfaceId": "1000369、1000817",
  "contract": "",
  "contact": "",
  "todo": "",
  "daily": "",
  "groups": "",
  "notes": "接口提供方ID 1000109；供货方ID 1000238；结算方ID 1000410；接口数 2",
  "settleDetail": "单笔佣金 23.7400",
  "risk": "",
  "status": "进行中",
  "sub": []
 },
 {
  "type": "代理商",
  "region": "南区",
  "name": "广州码上购科技有限公司",
  "short": "广州码上购",
  "province": "广东",
  "operator": "",
  "productType": "存量",
  "settle": "T+1:21.0000",
  "interfaceId": "1000847、1000852",
  "contract": "",
  "contact": "",
  "todo": "",
  "daily": "",
  "groups": "",
  "notes": "接口提供方ID 1001146；供货方ID 1001139；结算方ID 1001140；接口数 2",
  "settleDetail": "单笔佣金 21.0000",
  "risk": "",
  "status": "进行中",
  "sub": []
 },
 {
  "type": "代理商",
  "region": "南区",
  "name": "杭州致柔软件有限公司",
  "short": "杭州致柔",
  "province": "浙江",
  "operator": "",
  "productType": "存量",
  "settle": "T+1:18.0000",
  "interfaceId": "1000858",
  "contract": "",
  "contact": "",
  "todo": "",
  "daily": "",
  "groups": "",
  "notes": "接口提供方ID 1001210；供货方ID 1001204；结算方ID 1001172；接口数 1",
  "settleDetail": "单笔佣金 18.0000",
  "risk": "",
  "status": "进行中",
  "sub": []
 },
 {
  "type": "代理商",
  "region": "南区",
  "name": "杭州妙壹科技有限公司",
  "short": "杭州妙壹",
  "province": "浙江",
  "operator": "",
  "productType": "存量",
  "settle": "T+1:12.0000",
  "interfaceId": "1000804",
  "contract": "",
  "contact": "",
  "todo": "",
  "daily": "",
  "groups": "",
  "notes": "接口提供方ID 1001013；供货方ID -；结算方ID 1001018；接口数 1",
  "settleDetail": "单笔佣金 12.0000",
  "risk": "",
  "status": "进行中",
  "sub": []
 },
 {
  "type": "代理商",
  "region": "南区",
  "name": "成都甜尖尖科技有限公司",
  "short": "成都甜尖尖",
  "province": "四川",
  "operator": "",
  "productType": "存量",
  "settle": "T+1:20.0000",
  "interfaceId": "1000869",
  "contract": "",
  "contact": "",
  "todo": "",
  "daily": "",
  "groups": "",
  "notes": "接口提供方ID 1001234；供货方ID 1001228；结算方ID 1001229；接口数 1",
  "settleDetail": "单笔佣金 20.0000",
  "risk": "",
  "status": "进行中",
  "sub": []
 },
 {
  "type": "代理商",
  "region": "南区",
  "name": "南京舜卓信息技术有限公司",
  "short": "南京舜卓",
  "province": "江苏",
  "operator": "",
  "productType": "存量",
  "settle": "T+1:18.0000",
  "interfaceId": "1000878",
  "contract": "",
  "contact": "",
  "todo": "",
  "daily": "",
  "groups": "",
  "notes": "接口提供方ID 1001246；供货方ID 1001240；结算方ID 1001241；接口数 1",
  "settleDetail": "单笔佣金 18.0000",
  "risk": "",
  "status": "进行中",
  "sub": []
 }
];
const SEED_PRODUCTS={
 "stock": [
  {
   "offerId": "1006443_106484_14247",
   "name": "联通-浙江13元10GB5日包",
   "amount": "13",
   "operator": "联通",
   "supplier": "中国联合网络通信有限公司浙江省分公司（全客）",
   "skuStatus": "上架",
   "status": "开启",
   "interfaceId": "1000450"
  },
  {
   "offerId": "1006436_106477_14240",
   "name": "联通-浙江30元20GB月包",
   "amount": "30",
   "operator": "联通",
   "supplier": "中国联合网络通信有限公司浙江省分公司（全客）",
   "skuStatus": "上架",
   "status": "开启",
   "interfaceId": "1000450"
  },
  {
   "offerId": "1005440_105378_12922",
   "name": "联通-浙江29元5GB通用+10GB定向流量权益组合包",
   "amount": "29",
   "operator": "联通",
   "supplier": "中国联合网络通信有限公司浙江省分公司（全客）",
   "skuStatus": "上架",
   "status": "开启",
   "interfaceId": "1000450"
  },
  {
   "offerId": "1003719_103573_10933",
   "name": "联通-浙江35元25GB10天包",
   "amount": "35",
   "operator": "联通",
   "supplier": "中国联合网络通信有限公司浙江省分公司（全客）",
   "skuStatus": "上架",
   "status": "开启",
   "interfaceId": "1000450"
  },
  {
   "offerId": "1003122_102953_10164",
   "name": "联通-浙江29元10GB5G月包",
   "amount": "29",
   "operator": "联通",
   "supplier": "中国联合网络通信有限公司浙江省分公司（全客）",
   "skuStatus": "上架",
   "status": "开启",
   "interfaceId": "1000450"
  },
  {
   "offerId": "1003121_102952_10163",
   "name": "联通-浙江19元5GB5G月包",
   "amount": "19",
   "operator": "联通",
   "supplier": "中国联合网络通信有限公司浙江省分公司（全客）",
   "skuStatus": "上架",
   "status": "开启",
   "interfaceId": "1000450"
  },
  {
   "offerId": "1003069_102904_10105",
   "name": "联通-浙江20元7GB7天包",
   "amount": "20",
   "operator": "联通",
   "supplier": "中国联合网络通信有限公司浙江省分公司（全客）",
   "skuStatus": "上架",
   "status": "开启",
   "interfaceId": "1000450"
  },
  {
   "offerId": "1006576_106636_14423",
   "name": "电信-杭州29元20GB橙翼礼券包",
   "amount": "29",
   "operator": "电信",
   "supplier": "中国电信股份有限公司杭州分公司",
   "skuStatus": "上架",
   "status": "开启",
   "interfaceId": "1000832"
  },
  {
   "offerId": "1006575_106635_14422",
   "name": "电信-杭州9.9元5GB橙翼礼券包",
   "amount": "9.9",
   "operator": "电信",
   "supplier": "中国电信股份有限公司杭州分公司",
   "skuStatus": "上架",
   "status": "开启",
   "interfaceId": "1000832"
  },
  {
   "offerId": "1006551_106610_14395",
   "name": "电信-杭州20元10GB5G-A优享包",
   "amount": "20",
   "operator": "电信",
   "supplier": "中国电信股份有限公司杭州分公司",
   "skuStatus": "上架",
   "status": "开启",
   "interfaceId": "1000832"
  },
  {
   "offerId": "1006239_106256_14013",
   "name": "电信-杭州10元40GB月包（24个月）",
   "amount": "10",
   "operator": "电信",
   "supplier": "中国电信股份有限公司杭州分公司",
   "skuStatus": "上架",
   "status": "开启",
   "interfaceId": "1000832"
  },
  {
   "offerId": "45961_9655",
   "name": "移动-广西网龄回馈202512焕新版-月租10元-承诺消费回馈100GB流量-24个月（当月生效）",
   "amount": "10",
   "operator": "移动",
   "supplier": "广西移动",
   "skuStatus": "上架",
   "status": "开启",
   "interfaceId": "1000807"
  },
  {
   "offerId": "46039_9477",
   "name": "移动-广西19.9元随心看-20GB定向流量翻倍活动-6个月",
   "amount": "19.9",
   "operator": "移动",
   "supplier": "广西移动",
   "skuStatus": "上架",
   "status": "关闭",
   "interfaceId": "1000807"
  },
  {
   "offerId": "gxdx_01",
   "name": "电信-广西20元消费品牌联名权益包B（淘票票）",
   "amount": "20",
   "operator": "电信",
   "supplier": "广西电信",
   "skuStatus": "上架",
   "status": "开启",
   "interfaceId": "1000833"
  },
  {
   "offerId": "gxdx_02",
   "name": "电信-广西20元消费品牌联名权益包B（古茗）",
   "amount": "20",
   "operator": "电信",
   "supplier": "广西电信",
   "skuStatus": "上架",
   "status": "开启",
   "interfaceId": "1000833"
  },
  {
   "offerId": "gxdx_03",
   "name": "电信-广西20元消费品牌联名权益包B（大参林）",
   "amount": "20",
   "operator": "电信",
   "supplier": "广西电信",
   "skuStatus": "上架",
   "status": "开启",
   "interfaceId": "1000833"
  },
  {
   "offerId": "gxdx_04",
   "name": "电信-广西25元霸王茶姬畅饮权益包",
   "amount": "25",
   "operator": "电信",
   "supplier": "广西电信",
   "skuStatus": "上架",
   "status": "开启",
   "interfaceId": ""
  },
  {
   "offerId": "gxdx_05",
   "name": "电信-广西10元5GB月包",
   "amount": "10",
   "operator": "电信",
   "supplier": "广西电信",
   "skuStatus": "上架",
   "status": "开启",
   "interfaceId": "1000291"
  },
  {
   "offerId": "gxdx_06",
   "name": "电信-广西20元霸王茶姬轻享权益包",
   "amount": "20",
   "operator": "电信",
   "supplier": "广西电信",
   "skuStatus": "上架",
   "status": "开启",
   "interfaceId": ""
  },
  {
   "offerId": "gxdx_07",
   "name": "电信-广西3日短期流量包4GB",
   "amount": "10",
   "operator": "电信",
   "supplier": "广西电信",
   "skuStatus": "上架",
   "status": "关闭",
   "interfaceId": "1000291"
  },
  {
   "offerId": "gxdx_08",
   "name": "电信-广西1日短期流量包5GB",
   "amount": "10",
   "operator": "电信",
   "supplier": "广西电信",
   "skuStatus": "上架",
   "status": "关闭",
   "interfaceId": "1000291"
  },
  {
   "offerId": "gxdx_09",
   "name": "电信-广西20元消费品牌联名权益包B（出行）",
   "amount": "20",
   "operator": "电信",
   "supplier": "广西电信",
   "skuStatus": "上架",
   "status": "开启",
   "interfaceId": "1000833"
  },
  {
   "offerId": "gxdx_10",
   "name": "电信-广西20元消费品牌联名权益包B（淘票票2）",
   "amount": "20",
   "operator": "电信",
   "supplier": "广西电信",
   "skuStatus": "上架",
   "status": "开启",
   "interfaceId": "1000833"
  },
  {
   "offerId": "gxdx_11",
   "name": "电信-广西7日短期流量包10GB",
   "amount": "20",
   "operator": "电信",
   "supplier": "广西电信",
   "skuStatus": "上架",
   "status": "关闭",
   "interfaceId": "1000291"
  },
  {
   "offerId": "gxdx_12",
   "name": "电信-广西5日短期流量包7GB",
   "amount": "15",
   "operator": "电信",
   "supplier": "广西电信",
   "skuStatus": "上架",
   "status": "关闭",
   "interfaceId": "1000291"
  },
  {
   "offerId": "gxdx_13",
   "name": "电信-广西20元4GB流量抖音本地生活权益包",
   "amount": "20",
   "operator": "电信",
   "supplier": "广西电信",
   "skuStatus": "上架",
   "status": "开启",
   "interfaceId": "1000291"
  },
  {
   "offerId": "gxdx_14",
   "name": "电信-广西20元5GB生活畅享福袋权益包",
   "amount": "20",
   "operator": "电信",
   "supplier": "广西电信",
   "skuStatus": "上架",
   "status": "开启",
   "interfaceId": "1000291"
  },
  {
   "offerId": "sdlt_01",
   "name": "联通-山东30元30GB14天包",
   "amount": "30",
   "operator": "联通",
   "supplier": "山东联通",
   "skuStatus": "上架",
   "status": "开启",
   "interfaceId": ""
  },
  {
   "offerId": "hndx_01",
   "name": "电信-湖南15元10GB月包202404",
   "amount": "15",
   "operator": "电信",
   "supplier": "湖南电信",
   "skuStatus": "上架",
   "status": "开启",
   "interfaceId": "1000559"
  },
  {
   "offerId": "hndx_02",
   "name": "电信-湖南20元5GB提速包202404",
   "amount": "20",
   "operator": "电信",
   "supplier": "湖南电信",
   "skuStatus": "上架",
   "status": "开启",
   "interfaceId": "1000559"
  },
  {
   "offerId": "hnlt_01",
   "name": "联通-湖南30元25GB7天包",
   "amount": "30",
   "operator": "联通",
   "supplier": "湖南联通",
   "skuStatus": "上架",
   "status": "开启",
   "interfaceId": "1000300"
  },
  {
   "offerId": "sdlt_02",
   "name": "联通-山东20元12GB流量月包",
   "amount": "20",
   "operator": "联通",
   "supplier": "山东联通",
   "skuStatus": "上架",
   "status": "开启",
   "interfaceId": ""
  },
  {
   "offerId": "sddx_01",
   "name": "电信-山东19元10GB通信流量包",
   "amount": "19",
   "operator": "电信",
   "supplier": "山东电信",
   "skuStatus": "上架",
   "status": "开启",
   "interfaceId": ""
  },
  {
   "offerId": "hnlt_02",
   "name": "联通-湖南15元10GB7天包",
   "amount": "15",
   "operator": "联通",
   "supplier": "湖南联通",
   "skuStatus": "上架",
   "status": "开启",
   "interfaceId": "1000300"
  },
  {
   "offerId": "hndx_03",
   "name": "电信-湖南20元20GB加餐包202404",
   "amount": "20",
   "operator": "电信",
   "supplier": "湖南电信",
   "skuStatus": "上架",
   "status": "开启",
   "interfaceId": "1000559"
  },
  {
   "offerId": "sdlt_03",
   "name": "联通-山东19.9元20GB8天包",
   "amount": "19.9",
   "operator": "联通",
   "supplier": "山东联通",
   "skuStatus": "上架",
   "status": "开启",
   "interfaceId": ""
  },
  {
   "offerId": "hnlt_03",
   "name": "联通-湖南10元8GB月末流量包",
   "amount": "10",
   "operator": "联通",
   "supplier": "湖南联通",
   "skuStatus": "上架",
   "status": "开启",
   "interfaceId": "1000300"
  },
  {
   "offerId": "hndx_04",
   "name": "电信-湖南50元40GB月包202404",
   "amount": "50",
   "operator": "电信",
   "supplier": "湖南电信",
   "skuStatus": "上架",
   "status": "开启",
   "interfaceId": "1000559"
  },
  {
   "offerId": "hndx_05",
   "name": "电信-湖南5元5GB月包202404",
   "amount": "5",
   "operator": "电信",
   "supplier": "湖南电信",
   "skuStatus": "上架",
   "status": "开启",
   "interfaceId": "1000559"
  },
  {
   "offerId": "hndx_06",
   "name": "电信-湖南互联网畅享权益包5GB15元",
   "amount": "15",
   "operator": "电信",
   "supplier": "湖南电信",
   "skuStatus": "上架",
   "status": "开启",
   "interfaceId": ""
  },
  {
   "offerId": "sdlt_04",
   "name": "联通-山东30元20GB流量月包",
   "amount": "30",
   "operator": "联通",
   "supplier": "山东联通",
   "skuStatus": "上架",
   "status": "开启",
   "interfaceId": ""
  },
  {
   "offerId": "sdlt_05",
   "name": "联通-山东10元5GB流量月包",
   "amount": "10",
   "operator": "联通",
   "supplier": "山东联通",
   "skuStatus": "上架",
   "status": "开启",
   "interfaceId": ""
  },
  {
   "offerId": "sddx_02",
   "name": "电信-山东20元10GB视频彩铃融合流量包",
   "amount": "20",
   "operator": "电信",
   "supplier": "山东电信",
   "skuStatus": "上架",
   "status": "开启",
   "interfaceId": ""
  },
  {
   "offerId": "hnlt_04",
   "name": "联通-湖南30元40GB月末流量包",
   "amount": "30",
   "operator": "联通",
   "supplier": "湖南联通",
   "skuStatus": "上架",
   "status": "开启",
   "interfaceId": "1000300"
  },
  {
   "offerId": "hndx_07",
   "name": "电信-湖南20元20GB月包202404",
   "amount": "20",
   "operator": "电信",
   "supplier": "湖南电信",
   "skuStatus": "上架",
   "status": "开启",
   "interfaceId": "1000559"
  },
  {
   "offerId": "hndx_08",
   "name": "电信-湖南10元5GB月包202404",
   "amount": "10",
   "operator": "电信",
   "supplier": "湖南电信",
   "skuStatus": "上架",
   "status": "开启",
   "interfaceId": "1000559"
  },
  {
   "offerId": "hndx_09",
   "name": "电信-湖南卫星+流量组合包（连续包月）",
   "amount": "29",
   "operator": "电信",
   "supplier": "湖南电信",
   "skuStatus": "上架",
   "status": "开启",
   "interfaceId": "1000405"
  },
  {
   "offerId": "sdlt_06",
   "name": "联通-山东13元10GB5天包",
   "amount": "13",
   "operator": "联通",
   "supplier": "山东联通",
   "skuStatus": "上架",
   "status": "开启",
   "interfaceId": ""
  },
  {
   "offerId": "sdlt_07",
   "name": "联通-山东16元15GB8天包",
   "amount": "16",
   "operator": "联通",
   "supplier": "山东联通",
   "skuStatus": "上架",
   "status": "开启",
   "interfaceId": ""
  },
  {
   "offerId": "hnlt_05",
   "name": "联通-湖南20元20GB下旬加油包（续订版）",
   "amount": "20",
   "operator": "联通",
   "supplier": "湖南联通",
   "skuStatus": "上架",
   "status": "开启",
   "interfaceId": "1000300"
  },
  {
   "offerId": "hndx_10",
   "name": "电信-湖南30元20G月包",
   "amount": "30",
   "operator": "电信",
   "supplier": "湖南电信",
   "skuStatus": "上架",
   "status": "开启",
   "interfaceId": "1000559"
  },
  {
   "offerId": "hnlt_06",
   "name": "联通-湖南5元2GB日包",
   "amount": "0",
   "operator": "联通",
   "supplier": "湖南联通",
   "skuStatus": "上架",
   "status": "开启",
   "interfaceId": "1000300"
  },
  {
   "offerId": "sdlt_08",
   "name": "联通-山东20元15GB5天包",
   "amount": "20",
   "operator": "联通",
   "supplier": "山东联通",
   "skuStatus": "上架",
   "status": "开启",
   "interfaceId": ""
  },
  {
   "offerId": "hnlt_07",
   "name": "联通-湖南10元8GB下旬加油包（续订版）",
   "amount": "10",
   "operator": "联通",
   "supplier": "湖南联通",
   "skuStatus": "上架",
   "status": "开启",
   "interfaceId": "1000300"
  },
  {
   "offerId": "sdlt_09",
   "name": "联通-山东20元14GB7天包",
   "amount": "20",
   "operator": "联通",
   "supplier": "山东联通",
   "skuStatus": "上架",
   "status": "开启",
   "interfaceId": ""
  },
  {
   "offerId": "hnlt_08",
   "name": "联通-湖南乐享视频彩铃流量5G加油包-19元档（立即）",
   "amount": "19",
   "operator": "联通",
   "supplier": "湖南联通",
   "skuStatus": "上架",
   "status": "开启",
   "interfaceId": "1000300"
  },
  {
   "offerId": "hndx_11",
   "name": "电信-湖南10元10GB月包202404",
   "amount": "10",
   "operator": "电信",
   "supplier": "湖南电信",
   "skuStatus": "上架",
   "status": "开启",
   "interfaceId": "1000559"
  },
  {
   "offerId": "sdlt_10",
   "name": "联通-山东30元15GB流量月包（首月半价）",
   "amount": "30",
   "operator": "联通",
   "supplier": "山东联通",
   "skuStatus": "上架",
   "status": "开启",
   "interfaceId": ""
  },
  {
   "offerId": "hnlt_09",
   "name": "联通-湖南乐享视频彩铃流量5G加油包-29元档（立即）",
   "amount": "29",
   "operator": "联通",
   "supplier": "湖南联通",
   "skuStatus": "上架",
   "status": "开启",
   "interfaceId": "1000300"
  },
  {
   "offerId": "hndx_12",
   "name": "电信-湖南30元20GB月包202404",
   "amount": "30",
   "operator": "电信",
   "supplier": "湖南电信",
   "skuStatus": "上架",
   "status": "开启",
   "interfaceId": "1000559"
  },
  {
   "offerId": "sdlt_11",
   "name": "联通-山东15元10GB3天包",
   "amount": "15",
   "operator": "联通",
   "supplier": "山东联通",
   "skuStatus": "上架",
   "status": "开启",
   "interfaceId": ""
  },
  {
   "offerId": "hnlt_10",
   "name": "联通-湖南25元视频彩铃流量组合包A-xq-ml",
   "amount": "25",
   "operator": "联通",
   "supplier": "湖南联通",
   "skuStatus": "上架",
   "status": "开启",
   "interfaceId": ""
  },
  {
   "offerId": "hnlt_11",
   "name": "联通-湖南乐享视频彩铃流量5G加油包-16元档（立即）",
   "amount": "16",
   "operator": "联通",
   "supplier": "湖南联通",
   "skuStatus": "上架",
   "status": "开启",
   "interfaceId": "1000300"
  },
  {
   "offerId": "sdlt_12",
   "name": "联通-山东40元40GB14天包",
   "amount": "40",
   "operator": "联通",
   "supplier": "山东联通",
   "skuStatus": "上架",
   "status": "开启",
   "interfaceId": ""
  },
  {
   "offerId": "hndx_13",
   "name": "电信-湖南天翼云电脑基础版（30元/月）",
   "amount": "30",
   "operator": "电信",
   "supplier": "湖南电信",
   "skuStatus": "上架",
   "status": "开启",
   "interfaceId": "1000405"
  },
  {
   "offerId": "hndx_14",
   "name": "电信-湖南20元10GB提速包202404",
   "amount": "20",
   "operator": "电信",
   "supplier": "湖南电信",
   "skuStatus": "上架",
   "status": "开启",
   "interfaceId": "1000559"
  },
  {
   "offerId": "sdlt_13",
   "name": "联通-山东20元10GB流量月包（首月半价）",
   "amount": "20",
   "operator": "联通",
   "supplier": "山东联通",
   "skuStatus": "上架",
   "status": "开启",
   "interfaceId": ""
  },
  {
   "offerId": "hnlt_12",
   "name": "联通-湖南3元1GB日包",
   "amount": "3",
   "operator": "联通",
   "supplier": "湖南联通",
   "skuStatus": "下架",
   "status": "关闭",
   "interfaceId": "1000300"
  },
  {
   "offerId": "sddx_03",
   "name": "电信-山东20元10GB天翼云盘流量包",
   "amount": "20",
   "operator": "电信",
   "supplier": "山东电信",
   "skuStatus": "上架",
   "status": "开启",
   "interfaceId": ""
  },
  {
   "offerId": "sdlt_14",
   "name": "联通-山东40元27GB流量月包",
   "amount": "40",
   "operator": "联通",
   "supplier": "山东联通",
   "skuStatus": "上架",
   "status": "开启",
   "interfaceId": ""
  },
  {
   "offerId": "hnlt_13",
   "name": "联通-湖南10元3GB三日包",
   "amount": "10",
   "operator": "联通",
   "supplier": "湖南联通",
   "skuStatus": "上架",
   "status": "开启",
   "interfaceId": "1000300"
  },
  {
   "offerId": "hndx_15",
   "name": "电信-湖南网易云音乐会员权益流量包（19.9元5GB+网易云",
   "amount": "19.9",
   "operator": "电信",
   "supplier": "湖南电信",
   "skuStatus": "上架",
   "status": "开启",
   "interfaceId": "1000405"
  },
  {
   "offerId": "hnlt_14",
   "name": "联通-湖南10元15GB夜间月包",
   "amount": "0",
   "operator": "联通",
   "supplier": "湖南联通",
   "skuStatus": "上架",
   "status": "开启",
   "interfaceId": "1000300"
  },
  {
   "offerId": "sdlt_15",
   "name": "联通-山东6元2GB日包",
   "amount": "6",
   "operator": "联通",
   "supplier": "山东联通",
   "skuStatus": "上架",
   "status": "开启",
   "interfaceId": ""
  },
  {
   "offerId": "sdlt_16",
   "name": "联通-山东20元20GB腾讯定向月包",
   "amount": "20",
   "operator": "联通",
   "supplier": "山东联通",
   "skuStatus": "上架",
   "status": "开启",
   "interfaceId": ""
  },
  {
   "offerId": "hndx_16",
   "name": "电信-湖南哔哩哔哩会员15GB定向流量包（19.9元/月）",
   "amount": "19.9",
   "operator": "电信",
   "supplier": "湖南电信",
   "skuStatus": "上架",
   "status": "开启",
   "interfaceId": "1000405"
  },
  {
   "offerId": "sdlt_17",
   "name": "联通-山东16元11GB3天包",
   "amount": "16",
   "operator": "联通",
   "supplier": "山东联通",
   "skuStatus": "上架",
   "status": "开启",
   "interfaceId": ""
  },
  {
   "offerId": "hndx_17",
   "name": "电信-湖南60元60GB月包202404",
   "amount": "60",
   "operator": "电信",
   "supplier": "湖南电信",
   "skuStatus": "上架",
   "status": "开启",
   "interfaceId": "1000559"
  },
  {
   "offerId": "dzh_01",
   "name": "电信-浙江15元通信助理IP包",
   "amount": "15",
   "operator": "电信",
   "supplier": "读赞",
   "skuStatus": "上架",
   "status": "开启",
   "interfaceId": ""
  },
  {
   "offerId": "gxdx_15",
   "name": "电信-广西20元消费品牌联名权益包B（古茗奶茶）",
   "amount": "20",
   "operator": "电信",
   "supplier": "广西电信",
   "skuStatus": "上架",
   "status": "开启",
   "interfaceId": "1000833"
  },
  {
   "offerId": "hnyd_01",
   "name": "移动-湖南12580每天惠白金版（35元=15G通用流量+30元购物优惠券）",
   "amount": "35",
   "operator": "移动",
   "supplier": "湖南移动",
   "skuStatus": "上架",
   "status": "关闭",
   "interfaceId": "1000674"
  },
  {
   "offerId": "hnyd_02",
   "name": "移动-湖南25元乒乓球畅享包-活色生湘版",
   "amount": "25",
   "operator": "移动",
   "supplier": "湖南移动",
   "skuStatus": "下架",
   "status": "关闭",
   "interfaceId": "1000674"
  },
  {
   "offerId": "hndx_18",
   "name": "电信-湖南互联网专享权益包5GB15元",
   "amount": "15",
   "operator": "电信",
   "supplier": "湖南电信",
   "skuStatus": "下架",
   "status": "开启",
   "interfaceId": "1000405"
  },
  {
   "offerId": "hndx_19",
   "name": "电信-湖南30元20GB月包20251118-跳转接口",
   "amount": "30",
   "operator": "电信",
   "supplier": "湖南电信",
   "skuStatus": "上架",
   "status": "关闭",
   "interfaceId": "1000816"
  },
  {
   "offerId": "gxyd_01",
   "name": "移动-广西12580每天惠白金会员(15元包月)",
   "amount": "15",
   "operator": "移动",
   "supplier": "广西移动",
   "skuStatus": "上架",
   "status": "关闭",
   "interfaceId": "1000807"
  },
  {
   "offerId": "hnyd_03",
   "name": "移动-湖南30元足球通畅享包-明星闹铃经济版",
   "amount": "30",
   "operator": "移动",
   "supplier": "湖南移动",
   "skuStatus": "下架",
   "status": "关闭",
   "interfaceId": "1000674"
  },
  {
   "offerId": "hnyd_04",
   "name": "移动-湖南5G新通话-AI速记1000分钟包",
   "amount": "20",
   "operator": "移动",
   "supplier": "湖南移动",
   "skuStatus": "下架",
   "status": "关闭",
   "interfaceId": "1000674"
  },
  {
   "offerId": "gxdx_16",
   "name": "电信-广西25元天猫福利权益流量包",
   "amount": "25",
   "operator": "电信",
   "supplier": "广西电信",
   "skuStatus": "上架",
   "status": "关闭",
   "interfaceId": "1000291"
  },
  {
   "offerId": "hnltxq_01",
   "name": "联通-湖南都市畅听流量组合包29元(xq)(9GB+热血都市畅听包）",
   "amount": "29",
   "operator": "联通",
   "supplier": "湖南联通(讯旗)",
   "skuStatus": "下架",
   "status": "关闭",
   "interfaceId": "1000716"
  },
  {
   "offerId": "hndx_20",
   "name": "电信-湖南30元20GB月包20251118",
   "amount": "30",
   "operator": "电信",
   "supplier": "湖南电信",
   "skuStatus": "上架",
   "status": "关闭",
   "interfaceId": "1000798"
  },
  {
   "offerId": "gxdx_17",
   "name": "电信-广西25元霸王茶姬畅饮权益包（适用畅享）",
   "amount": "25",
   "operator": "电信",
   "supplier": "广西电信",
   "skuStatus": "下架",
   "status": "开启",
   "interfaceId": "1000291"
  },
  {
   "offerId": "hnyd_05",
   "name": "移动-湖南移动甄选会员(每天惠白金版）",
   "amount": "30",
   "operator": "移动",
   "supplier": "湖南移动",
   "skuStatus": "下架",
   "status": "关闭",
   "interfaceId": "1000674"
  },
  {
   "offerId": "ats_01",
   "name": "移动-广东20元咪咕足球通月包",
   "amount": "20",
   "operator": "移动",
   "supplier": "安徽天枢",
   "skuStatus": "上架",
   "status": "关闭",
   "interfaceId": "1000810"
  },
  {
   "offerId": "hnltxq_02",
   "name": "联通-湖南云盘流量5G加油包-29元档",
   "amount": "29",
   "operator": "联通",
   "supplier": "湖南联通(讯旗)",
   "skuStatus": "上架",
   "status": "关闭",
   "interfaceId": "1000716"
  },
  {
   "offerId": "handx_01",
   "name": "电信-海南25元健康智选权益流量包",
   "amount": "25",
   "operator": "电信",
   "supplier": "海南电信",
   "skuStatus": "上架",
   "status": "关闭",
   "interfaceId": "1000831"
  },
  {
   "offerId": "hnltxq_03",
   "name": "联通-湖南25元视频彩铃流量组合包A（xq）",
   "amount": "25",
   "operator": "联通",
   "supplier": "湖南联通(讯旗)",
   "skuStatus": "上架",
   "status": "关闭",
   "interfaceId": "1000716"
  },
  {
   "offerId": "hnyd_06",
   "name": "移动-湖南动感地带芒果包-优惠版20元/月",
   "amount": "20",
   "operator": "移动",
   "supplier": "湖南移动",
   "skuStatus": "上架",
   "status": "开启",
   "interfaceId": "1000674"
  },
  {
   "offerId": "gxdx_18",
   "name": "电信-广西霸王茶姬轻享权益包20元",
   "amount": "20",
   "operator": "电信",
   "supplier": "广西电信",
   "skuStatus": "下架",
   "status": "开启",
   "interfaceId": "1000291"
  },
  {
   "offerId": "hnlt_15",
   "name": "联通-湖南30元25GB7天包-充流量",
   "amount": "30",
   "operator": "联通",
   "supplier": "湖南联通",
   "skuStatus": "上架",
   "status": "开启",
   "interfaceId": "1000300"
  },
  {
   "offerId": "hanlt_01",
   "name": "联通-海南5G云盘尊享会员流量包21元/月",
   "amount": "21",
   "operator": "联通",
   "supplier": "海南联通",
   "skuStatus": "上架",
   "status": "关闭",
   "interfaceId": "1000290"
  },
  {
   "offerId": "gzmsg_01",
   "name": "移动-广东移动-19元优享会员（A）-巨量msg",
   "amount": "19",
   "operator": "移动",
   "supplier": "广州码上购",
   "skuStatus": "下架",
   "status": "关闭",
   "interfaceId": "1000852"
  },
  {
   "offerId": "hndx_21",
   "name": "电信-湖南70元100GB月包202404",
   "amount": "70",
   "operator": "电信",
   "supplier": "湖南电信",
   "skuStatus": "下架",
   "status": "关闭",
   "interfaceId": "1000559"
  },
  {
   "offerId": "bjzwyh_01",
   "name": "移动-全国20元电竞包专项版-ks",
   "amount": "20",
   "operator": "移动",
   "supplier": "北京中网云合",
   "skuStatus": "上架",
   "status": "开启",
   "interfaceId": "1000859"
  },
  {
   "offerId": "hndx_22",
   "name": "电信-湖南30元20GB月包202404-T",
   "amount": "30",
   "operator": "电信",
   "supplier": "湖南电信",
   "skuStatus": "上架",
   "status": "开启",
   "interfaceId": "1000559"
  },
  {
   "offerId": "dzh_02",
   "name": "电信-浙江15元通信助理IP包（dzh）",
   "amount": "15",
   "operator": "电信",
   "supplier": "杭州大嘴猴",
   "skuStatus": "上架",
   "status": "开启",
   "interfaceId": "1000849"
  },
  {
   "offerId": "hanlt_02",
   "name": "联通-海南联通视频铂金会员5GB流量包20元/月（当月生效）（海南）-首月1元",
   "amount": "20",
   "operator": "联通",
   "supplier": "海南联通",
   "skuStatus": "上架",
   "status": "关闭",
   "interfaceId": "1000290"
  },
  {
   "offerId": "hnyd_07",
   "name": "移动-湖南订阅号-童话视铃畅玩版",
   "amount": "30",
   "operator": "移动",
   "supplier": "湖南移动",
   "skuStatus": "下架",
   "status": "关闭",
   "interfaceId": "1000674"
  },
  {
   "offerId": "bjzwyh_02",
   "name": "移动-全国20元电竞包专项版-jl",
   "amount": "20",
   "operator": "移动",
   "supplier": "北京中网云合",
   "skuStatus": "上架",
   "status": "开启",
   "interfaceId": "1000859"
  },
  {
   "offerId": "hndx_23",
   "name": "电信-湖南网易云音乐会员权益流量包（19.9元5GB+网易云-qy",
   "amount": "19.9",
   "operator": "电信",
   "supplier": "湖南电信",
   "skuStatus": "上架",
   "status": "开启",
   "interfaceId": "1000868"
  },
  {
   "offerId": "hnlt_16",
   "name": "联通-湖南3元1GB日包-充流量",
   "amount": "3",
   "operator": "联通",
   "supplier": "湖南联通",
   "skuStatus": "上架",
   "status": "开启",
   "interfaceId": "1000300"
  },
  {
   "offerId": "njxy_01",
   "name": "电信-广西20元喜马拉雅权益流量包xy",
   "amount": "20",
   "operator": "电信",
   "supplier": "南京新游",
   "skuStatus": "上架",
   "status": "关闭",
   "interfaceId": "1000664"
  },
  {
   "offerId": "gxyd_02",
   "name": "移动-广西爱奇艺白金联合会员合约",
   "amount": "19.9",
   "operator": "移动",
   "supplier": "广西移动",
   "skuStatus": "上架",
   "status": "关闭",
   "interfaceId": "1000807"
  },
  {
   "offerId": "handx_02",
   "name": "电信-海南29.9元10GB流量权益包（12个月）",
   "amount": "29.9",
   "operator": "电信",
   "supplier": "海南电信",
   "skuStatus": "上架",
   "status": "关闭",
   "interfaceId": "1000831"
  },
  {
   "offerId": "hzmy_01",
   "name": "电信-江苏天翼出行PLUS-VIP",
   "amount": "15",
   "operator": "电信",
   "supplier": "杭州妙壹",
   "skuStatus": "下架",
   "status": "关闭",
   "interfaceId": "1000804"
  },
  {
   "offerId": "hzzr_01",
   "name": "电信-贵州电信臻选-中石化权益包（连续包月）-zr",
   "amount": "20",
   "operator": "电信",
   "supplier": "杭州致柔",
   "skuStatus": "上架",
   "status": "开启",
   "interfaceId": "1000858"
  },
  {
   "offerId": "hanlt_03",
   "name": "联通-海南5G云盘尊享会员流量包18元/月",
   "amount": "18",
   "operator": "联通",
   "supplier": "海南联通",
   "skuStatus": "上架",
   "status": "关闭",
   "interfaceId": "1000290"
  },
  {
   "offerId": "gxyd_03",
   "name": "移动-广西网龄回馈202512焕新版-月租15元-承诺消费回馈200GB流量-24个月-当月生效",
   "amount": "15",
   "operator": "移动",
   "supplier": "广西移动",
   "skuStatus": "上架",
   "status": "开启",
   "interfaceId": "1000807"
  },
  {
   "offerId": "handx_03",
   "name": "电信-海南25元车主权益流量包",
   "amount": "25",
   "operator": "电信",
   "supplier": "海南电信",
   "skuStatus": "上架",
   "status": "关闭",
   "interfaceId": "1000831"
  },
  {
   "offerId": "handx_04",
   "name": "电信-海南25元8GB流量权益包（12个月）",
   "amount": "25",
   "operator": "电信",
   "supplier": "海南电信",
   "skuStatus": "上架",
   "status": "关闭",
   "interfaceId": "1000831"
  },
  {
   "offerId": "hzzr_02",
   "name": "电信-重庆电信臻选-中石化权益包（连续包月）-zr",
   "amount": "20",
   "operator": "电信",
   "supplier": "杭州致柔",
   "skuStatus": "上架",
   "status": "开启",
   "interfaceId": "1000858"
  },
  {
   "offerId": "hndx_24",
   "name": "电信-湖南哔哩哔哩会员15GB定向流量包（19.9元/月）-qy",
   "amount": "19.9",
   "operator": "电信",
   "supplier": "湖南电信",
   "skuStatus": "上架",
   "status": "开启",
   "interfaceId": "1000868"
  },
  {
   "offerId": "gxdx_19",
   "name": "电信-广西20元4GB流量抖音本地生活权益包(适用畅享)",
   "amount": "20",
   "operator": "电信",
   "supplier": "广西电信",
   "skuStatus": "上架",
   "status": "关闭",
   "interfaceId": "1000291"
  },
  {
   "offerId": "njxy_02",
   "name": "电信-云南/山西通助尊享版9元+数字人vip5元",
   "amount": "14",
   "operator": "电信",
   "supplier": "南京新游",
   "skuStatus": "上架",
   "status": "关闭",
   "interfaceId": "1000664"
  },
  {
   "offerId": "gzmsg_02",
   "name": "移动-多省移动-咪咕AI悦动包尊享版20元-msg",
   "amount": "20",
   "operator": "移动",
   "supplier": "广州码上购",
   "skuStatus": "上架",
   "status": "开启",
   "interfaceId": "1000852"
  },
  {
   "offerId": "hnlt_17",
   "name": "联通-湖南16元8GB+云盘白银会员",
   "amount": "0",
   "operator": "联通",
   "supplier": "湖南联通",
   "skuStatus": "上架",
   "status": "关闭",
   "interfaceId": "1000300"
  },
  {
   "offerId": "cdtjj_01",
   "name": "移动-吉林移动吉视秀精品会员颜控福利20元-tjj",
   "amount": "20",
   "operator": "移动",
   "supplier": "成都甜尖尖",
   "skuStatus": "上架",
   "status": "开启",
   "interfaceId": "1000869"
  },
  {
   "offerId": "hanlt_04",
   "name": "联通-海南5G云盘尊享会员权益N选1包15元/月（海南）-（立即生效）",
   "amount": "15",
   "operator": "联通",
   "supplier": "海南联通",
   "skuStatus": "上架",
   "status": "关闭",
   "interfaceId": "1000290"
  },
  {
   "offerId": "xmzl_01",
   "name": "电信-浙江15元通信助理智能版+通信助理数字人IP包-LLG",
   "amount": "15",
   "operator": "电信",
   "supplier": "厦门众联流量果",
   "skuStatus": "下架",
   "status": "关闭",
   "interfaceId": "1000817"
  },
  {
   "offerId": "gzmsg_03",
   "name": "电信-青海电信-19.9元橙翼包-msg",
   "amount": "19.9",
   "operator": "电信",
   "supplier": "广州码上购",
   "skuStatus": "上架",
   "status": "开启",
   "interfaceId": "1000847"
  },
  {
   "offerId": "gzmsg_04",
   "name": "移动-广西移动-网龄回馈202512焕新版15元msg",
   "amount": "15",
   "operator": "移动",
   "supplier": "广州码上购",
   "skuStatus": "下架",
   "status": "开启",
   "interfaceId": "1000847"
  },
  {
   "offerId": "ats_02",
   "name": "移动-河南25元咪咕短剧情感优享包",
   "amount": "25",
   "operator": "移动",
   "supplier": "安徽天枢",
   "skuStatus": "上架",
   "status": "关闭",
   "interfaceId": "1000810"
  },
  {
   "offerId": "gzmsg_05",
   "name": "移动-山西移动-晋出行联合会员20元-msg",
   "amount": "20",
   "operator": "移动",
   "supplier": "广州码上购",
   "skuStatus": "上架",
   "status": "开启",
   "interfaceId": "1000852"
  },
  {
   "offerId": "hzmy_02",
   "name": "电信-江苏天翼出行PLUS-优惠券包",
   "amount": "20",
   "operator": "电信",
   "supplier": "杭州妙壹",
   "skuStatus": "下架",
   "status": "关闭",
   "interfaceId": "1000804"
  },
  {
   "offerId": "gxdx_20",
   "name": "电信-广西10元5GB月包（适用畅享）",
   "amount": "10",
   "operator": "电信",
   "supplier": "广西电信",
   "skuStatus": "上架",
   "status": "关闭",
   "interfaceId": "1000291"
  },
  {
   "offerId": "xmzl_02",
   "name": "电信-新疆电信视频彩铃10元V2-LLG",
   "amount": "10",
   "operator": "电信",
   "supplier": "厦门众联流量果",
   "skuStatus": "下架",
   "status": "关闭",
   "interfaceId": "1000817"
  },
  {
   "offerId": "xmzl_03",
   "name": "联通-青海车主秘书金卡21.9元10GB-LLG",
   "amount": "21.9",
   "operator": "联通",
   "supplier": "厦门众联流量果",
   "skuStatus": "下架",
   "status": "关闭",
   "interfaceId": "1000817"
  },
  {
   "offerId": "gxdx_21",
   "name": "电信-广西20元5GB生活畅享福袋权益包(适用畅享)",
   "amount": "20",
   "operator": "电信",
   "supplier": "广西电信",
   "skuStatus": "上架",
   "status": "关闭",
   "interfaceId": "1000291"
  },
  {
   "offerId": "hnlt_18",
   "name": "联通-湖南5元3GB月末流量包",
   "amount": "16",
   "operator": "联通",
   "supplier": "湖南联通",
   "skuStatus": "上架",
   "status": "关闭",
   "interfaceId": "1000300"
  },
  {
   "offerId": "gzmsg_06",
   "name": "移动-广东移动-19元优享会员（A）-快手msg",
   "amount": "19",
   "operator": "移动",
   "supplier": "广州码上购",
   "skuStatus": "下架",
   "status": "关闭",
   "interfaceId": "1000852"
  },
  {
   "offerId": "hanlt_05",
   "name": "联通-海南5G云盘尊享会员流量包21元/月-旧",
   "amount": "21",
   "operator": "联通",
   "supplier": "海南联通",
   "skuStatus": "上架",
   "status": "关闭",
   "interfaceId": "1000290"
  },
  {
   "offerId": "handx_05",
   "name": "电信-海南29.9元健康尊享权益流量包",
   "amount": "29.9",
   "operator": "电信",
   "supplier": "海南电信",
   "skuStatus": "下架",
   "status": "关闭",
   "interfaceId": "1000733"
  },
  {
   "offerId": "gxdx_22",
   "name": "电信-广西优酷会员权益2GB通用流量包（连续包月）",
   "amount": "23.9",
   "operator": "电信",
   "supplier": "广西电信",
   "skuStatus": "下架",
   "status": "关闭",
   "interfaceId": "1000291"
  },
  {
   "offerId": "gdsy_01",
   "name": "移动-广东-咪咕短剧超级会员-20元（SY）",
   "amount": "20",
   "operator": "移动",
   "supplier": "广东森越",
   "skuStatus": "上架",
   "status": "关闭",
   "interfaceId": "1000732"
  },
  {
   "offerId": "hnyd_08",
   "name": "移动-湖南5G新通话-明星来电白银组合包B",
   "amount": "15",
   "operator": "移动",
   "supplier": "湖南移动",
   "skuStatus": "下架",
   "status": "关闭",
   "interfaceId": "1000796"
  },
  {
   "offerId": "xmzl_04",
   "name": "电信-宁夏电信天翼超高清plus18元-llg",
   "amount": "18",
   "operator": "电信",
   "supplier": "厦门众联流量果",
   "skuStatus": "上架",
   "status": "关闭",
   "interfaceId": "1000817"
  },
  {
   "offerId": "gzmsg_07",
   "name": "移动-多省移动-咪咕音乐天籁包-msg",
   "amount": "18",
   "operator": "移动",
   "supplier": "广州码上购",
   "skuStatus": "下架",
   "status": "开启",
   "interfaceId": "1000847"
  },
  {
   "offerId": "ats_03",
   "name": "移动-上海36.9元4GB流量便利蜂权益组合包",
   "amount": "36.9",
   "operator": "移动",
   "supplier": "安徽天枢",
   "skuStatus": "上架",
   "status": "关闭",
   "interfaceId": "1000810"
  },
  {
   "offerId": "xmzl_05",
   "name": "电信-浙江电信通讯助理9元@9916-llg",
   "amount": "9",
   "operator": "电信",
   "supplier": "厦门众联流量果",
   "skuStatus": "下架",
   "status": "关闭",
   "interfaceId": "1000817"
  },
  {
   "offerId": "xmzl_06",
   "name": "电信-新疆电信蘑菇云游戏20元-llg",
   "amount": "20",
   "operator": "电信",
   "supplier": "厦门众联流量果",
   "skuStatus": "下架",
   "status": "关闭",
   "interfaceId": "1000817"
  },
  {
   "offerId": "gzmsg_08",
   "name": "移动-广东移动-25元优享会员-巨量msg",
   "amount": "25",
   "operator": "移动",
   "supplier": "广州码上购",
   "skuStatus": "下架",
   "status": "关闭",
   "interfaceId": "1000847"
  },
  {
   "offerId": "gzmsg_09",
   "name": "移动-山东移动铃视会员体育版19.9元-msg",
   "amount": "19.9",
   "operator": "移动",
   "supplier": "广州码上购",
   "skuStatus": "下架",
   "status": "关闭",
   "interfaceId": "1000847"
  },
  {
   "offerId": "hanlt_06",
   "name": "联通-海南5G宽视界钻享会员首月特惠包6元/月（海南）-立即生效",
   "amount": "6",
   "operator": "联通",
   "supplier": "海南联通",
   "skuStatus": "下架",
   "status": "关闭",
   "interfaceId": "1000290"
  },
  {
   "offerId": "gzmsg_10",
   "name": "电信-天津电信-津享生活会员-15元-msg",
   "amount": "15",
   "operator": "电信",
   "supplier": "广州码上购",
   "skuStatus": "上架",
   "status": "开启",
   "interfaceId": "1000852"
  },
  {
   "offerId": "cdtjj_02",
   "name": "电信-安徽电信29.9元权益随心选出行版-tjj",
   "amount": "29.9",
   "operator": "电信",
   "supplier": "成都甜尖尖",
   "skuStatus": "上架",
   "status": "开启",
   "interfaceId": "1000869"
  },
  {
   "offerId": "zyhlw_01",
   "name": "移动-全国20元云盘黄金会员（ZYH）",
   "amount": "20",
   "operator": "移动",
   "supplier": "中移互联网",
   "skuStatus": "上架",
   "status": "开启",
   "interfaceId": "1000875"
  },
  {
   "offerId": "hnyd_09",
   "name": "移动-湖南25元订阅号-新华每日播报尊享升级版",
   "amount": "25",
   "operator": "移动",
   "supplier": "湖南移动",
   "skuStatus": "上架",
   "status": "关闭",
   "interfaceId": "1000674"
  },
  {
   "offerId": "hnyd_10",
   "name": "移动-湖南乒乓球畅享包-童话视铃版30元",
   "amount": "30",
   "operator": "移动",
   "supplier": "湖南移动",
   "skuStatus": "下架",
   "status": "关闭",
   "interfaceId": "1000674"
  },
  {
   "offerId": "hnyd_11",
   "name": "移动-湖南随心看彩铃版（炫视专属版）28元8GB",
   "amount": "28",
   "operator": "移动",
   "supplier": "湖南移动",
   "skuStatus": "下架",
   "status": "关闭",
   "interfaceId": "1000674"
  },
  {
   "offerId": "hnyd_12",
   "name": "移动-湖南30元足球通畅享包-湘视秀版",
   "amount": "30",
   "operator": "移动",
   "supplier": "湖南移动",
   "skuStatus": "上架",
   "status": "关闭",
   "interfaceId": "1000674"
  },
  {
   "offerId": "hnyd_13",
   "name": "移动-湖南湘视秀6元/月",
   "amount": "6",
   "operator": "移动",
   "supplier": "湖南移动",
   "skuStatus": "上架",
   "status": "关闭",
   "interfaceId": "1000674"
  },
  {
   "offerId": "hnyd_14",
   "name": "移动-湖南15元视频彩铃精品荟",
   "amount": "15",
   "operator": "移动",
   "supplier": "湖南移动",
   "skuStatus": "上架",
   "status": "关闭",
   "interfaceId": "1000674"
  },
  {
   "offerId": "hnyd_15",
   "name": "移动-湖南视频彩铃精品荟-尊享升级版",
   "amount": "25",
   "operator": "移动",
   "supplier": "湖南移动",
   "skuStatus": "上架",
   "status": "开启",
   "interfaceId": "1000674"
  },
  {
   "offerId": "xmzl_07",
   "name": "电信-吉林流量车服合约14.9元5GB-LLG",
   "amount": "14.9",
   "operator": "电信",
   "supplier": "厦门众联流量果",
   "skuStatus": "下架",
   "status": "关闭",
   "interfaceId": "1000817"
  },
  {
   "offerId": "xmzl_08",
   "name": "电信-全国中石化权益包20元-LLG",
   "amount": "20",
   "operator": "电信",
   "supplier": "厦门众联流量果",
   "skuStatus": "下架",
   "status": "关闭",
   "interfaceId": "1000817"
  },
  {
   "offerId": "gzmsg_11",
   "name": "移动-广东移动-25元优享会员-快手msg",
   "amount": "25",
   "operator": "移动",
   "supplier": "广州码上购",
   "skuStatus": "下架",
   "status": "关闭",
   "interfaceId": "1000847"
  },
  {
   "offerId": "gzmsg_12",
   "name": "电信-山西电信-视听娱乐权益包(N选2)+2GB全国通用流量-msg",
   "amount": "19.9",
   "operator": "电信",
   "supplier": "广州码上购",
   "skuStatus": "下架",
   "status": "开启",
   "interfaceId": "1000847"
  },
  {
   "offerId": "bjzwyh_03",
   "name": "移动-全国20元电竞包专项版-湖北ks",
   "amount": "20",
   "operator": "移动",
   "supplier": "北京中网云合",
   "skuStatus": "上架",
   "status": "开启",
   "interfaceId": "1000859"
  },
  {
   "offerId": "cdtjj_03",
   "name": "电信-天津电信津享生活会员5GB合约版15元-tjj",
   "amount": "15",
   "operator": "电信",
   "supplier": "成都甜尖尖",
   "skuStatus": "下架",
   "status": "关闭",
   "interfaceId": "1000869"
  },
  {
   "offerId": "zyhlw_02",
   "name": "移动-全国25元云盘黄金AI会员（ZYH）",
   "amount": "25",
   "operator": "移动",
   "supplier": "中移互联网",
   "skuStatus": "上架",
   "status": "开启",
   "interfaceId": "1000875"
  }
 ],
 "broadband": [
  {
   "providerId": "10001419",
   "provider": "浙江赋能",
   "operator": "中国电信",
   "productNo": "12026022610865107",
   "name": "杭州电信300M宽带新装一年支付宝",
   "commissionType": "商机单类",
   "channel": "支付宝,光华平台,小程序,抖音店铺",
   "city": "杭州市",
   "rate": "300M",
   "contract": "12个月",
   "price": "480.00",
   "monthly": "40.00",
   "audit": "通过",
   "shelf": "已上架",
   "commission": "40.00"
  },
  {
   "providerId": "10001419",
   "provider": "浙江赋能",
   "operator": "中国电信",
   "productNo": "12026031610865127",
   "name": "杭州电信1000M宽带新装一年高德",
   "commissionType": "商机单类",
   "channel": "高德,抖音店铺",
   "city": "杭州市",
   "rate": "1000M",
   "contract": "12个月",
   "price": "1200.00",
   "monthly": "100.00",
   "audit": "通过",
   "shelf": "已上架",
   "commission": "40.00"
  },
  {
   "providerId": "10001419",
   "provider": "浙江赋能",
   "operator": "中国电信",
   "productNo": "12026022610865108",
   "name": "杭州电信100M宽带新装一年支付宝",
   "commissionType": "商机单类",
   "channel": "支付宝,光华平台,小程序,抖音店铺",
   "city": "杭州市",
   "rate": "100M",
   "contract": "12个月",
   "price": "480.00",
   "monthly": "40.00",
   "audit": "通过",
   "shelf": "已上架",
   "commission": "40.00"
  },
  {
   "providerId": "10001419",
   "provider": "浙江赋能",
   "operator": "中国电信",
   "productNo": "12026031610865124",
   "name": "杭州电信200M宽带新装一年高德",
   "commissionType": "商机单类",
   "channel": "高德,抖音店铺",
   "city": "杭州市",
   "rate": "200M",
   "contract": "12个月",
   "price": "599.00",
   "monthly": "50.00",
   "audit": "通过",
   "shelf": "已上架",
   "commission": "40.00"
  },
  {
   "providerId": "10001419",
   "provider": "浙江赋能",
   "operator": "中国电信",
   "productNo": "12026031610865125",
   "name": "杭州电信300M宽带新装一年高德",
   "commissionType": "商机单类",
   "channel": "高德,抖音店铺",
   "city": "杭州市",
   "rate": "300M",
   "contract": "12个月",
   "price": "480.00",
   "monthly": "40.00",
   "audit": "通过",
   "shelf": "已上架",
   "commission": "40.00"
  },
  {
   "providerId": "10001419",
   "provider": "浙江赋能",
   "operator": "中国电信",
   "productNo": "12026031610865126",
   "name": "杭州电信500M宽带新装一年高德",
   "commissionType": "商机单类",
   "channel": "高德,抖音店铺",
   "city": "杭州市",
   "rate": "500M",
   "contract": "12个月",
   "price": "720.00",
   "monthly": "60.00",
   "audit": "通过",
   "shelf": "已上架",
   "commission": "40.00"
  },
  {
   "providerId": "10001419",
   "provider": "浙江赋能",
   "operator": "中国电信",
   "productNo": "12026022610865110",
   "name": "杭州电信1000M宽带新装一年支付宝",
   "commissionType": "商机单类",
   "channel": "支付宝,光华平台,小程序,抖音店铺",
   "city": "杭州市",
   "rate": "1000M",
   "contract": "12个月",
   "price": "1200.00",
   "monthly": "100.00",
   "audit": "通过",
   "shelf": "已上架",
   "commission": "40.00"
  },
  {
   "providerId": "10001419",
   "provider": "浙江赋能",
   "operator": "中国电信",
   "productNo": "12026022610865106",
   "name": "杭州电信200M宽带新装一年支付宝",
   "commissionType": "商机单类",
   "channel": "支付宝,光华平台,小程序,抖音店铺",
   "city": "杭州市",
   "rate": "200M",
   "contract": "12个月",
   "price": "599.00",
   "monthly": "50.00",
   "audit": "通过",
   "shelf": "已上架",
   "commission": "40.00"
  },
  {
   "providerId": "10001419",
   "provider": "浙江赋能",
   "operator": "中国电信",
   "productNo": "12026031610865123",
   "name": "杭州电信100M宽带新装一年高德",
   "commissionType": "商机单类",
   "channel": "高德,抖音店铺",
   "city": "杭州市",
   "rate": "100M",
   "contract": "12个月",
   "price": "480.00",
   "monthly": "40.00",
   "audit": "通过",
   "shelf": "已上架",
   "commission": "40.00"
  },
  {
   "providerId": "10001419",
   "provider": "浙江赋能",
   "operator": "中国电信",
   "productNo": "12026022610865109",
   "name": "杭州电信500M宽带新装一年支付宝",
   "commissionType": "商机单类",
   "channel": "支付宝,光华平台,小程序,抖音店铺",
   "city": "杭州市",
   "rate": "500M",
   "contract": "12个月",
   "price": "720.00",
   "monthly": "60.00",
   "audit": "通过",
   "shelf": "已上架",
   "commission": "40.00"
  }
 ]
};
